### ISSUE TITLE
502 Bad Gateway when registering new user

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#100]
On the screen after pressing submit with username/email etc.

**Comment by filippomc** [comment]
The registration error wasrelated to ingress nginx proxy size.
Fixed by editing the nginx-ingress-controller and set value:
```yaml
data:
  "proxy-buffer-size": "16k"
```
See also https://andrewlock.net/fixing-nginx-upstream-sent-too-big-header-error-when-running-an-ingress-controller-in-kubernetes/
