### ISSUE TITLE
Add basic ownership info for workspaces

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#102]
Currently if a user makes a workspace public, any other user can open it and edit the contents. 

As a first step to prevent this (until cloning of public workspaces is implemented) can any available data on who created/last edited/opened the workspace be made accessible via the icon on the homepage (e.g. listed when the ... button is pressed)

**Comment by filippomc** [comment]
I propose to make public workspaces editable only by the administrator and the owner (see also #101)

**Comment by filippomc** [comment]
Added read-only workspaces functionality: workspaces are read-only for non owners (administrator excluded)

@pgleeson what about disabling the add resource button for read-only workspaces?

**Comment by pgleeson** [comment]
@filippomc Sure, best to disable that button when it's read only.
