### ISSUE TITLE
Add Resource not working

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#103]
I've tried Add new resource (not altering the name) to a few workspaces, but the addition of the resource just hangs (stays as clock). 
<img width="274" alt="Screenshot 2021-02-15 at 18 32 47" src="https://user-images.githubusercontent.com/1556687/107982600-3e054680-6fbc-11eb-9351-a92bfa7b6cc7.png">

**Comment by filippomc** [comment]
There are still cases in which the resource update hangs but it's not really clear how to replicate this.
Maybe the workspaces queue blocked so needing to restart the workspaces pod.
If it happens again, can you please add the workspace id and the time that happened? We can check the process logs and the queue with that information.

**Comment by filippomc** [comment]
Tried and worksing. Probably related to #123

**Comment by pgleeson** [comment]
Out of date
