### ISSUE TITLE
Delete a resource from a workspace

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#117]
The left drawer seems the right place, need to define the interaction.
- [x] Design mockups
- [x] Implementation

**Comment by filippomc** [comment]
![image.png](https://images.zenhubusercontent.com/5c4f23c24557275e4b89d83b/e34bc50e-04c6-4dc7-82df-416db09146e5)

**Comment by pgleeson** [comment]
Looks good. It still begs the question in a user's mind though: what's the difference between an nwb file (or json etc) on the mounted volume and an NWB file which is a "resource". I know they can make any file a resource now, but the closer power users get to seeing the local file system the more prospect for confusion.

Would it be possible to give a hover over label/tooltip for these, i.e. Ferguson.nwb shows: "file:/opt/workspace/Ferguson.nwb", master.zip shows: "dir:/opt/workspace/master", so it makes it clearer...?

**Comment by filippomc** [comment]
yes haven't thought about adding the path as an info for the user, agree it can be useful.
The idea of a resource is that it's something that can be directly opened with one of the featured applications, so applications will notify osb when creating new resources (see #108). As for resources created from command line, need to think more about it. One idea we can consider is a kind of "auto scan" that creates resources corresponding to the files in the system on osb.
