### ISSUE TITLE
Create repository backend

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#126]
Implement CRUD operations:
- Add a repository
- Layer to add repositories of different types
- Volume creation, ETL
- Add repository volume to all workspaces in read only mode
- Consider a way to add custom metadata
- Repositories have an "owner"

**Comment by zsinnema** [comment]
@filippomc as agreed for the repositories for now we don't create a repository pvc and only implement the "copy" to workspace functionality
