### ISSUE TITLE
Change homepage to show: Your workspaces; Featured workspaces; All public workspaces

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#129]
There is now a clear distinction between a featured workspace (set as "interesting" by administrators) and a public workspace (any user can set their workspace public). The latter is currently hidden from other users, they just see the featured ones and their own. The homepage should be updated to show any ws which a user has set public in a separate list. 

I can see @filippomc's point that the public ws can be considered like a google doc set to "anyone with the link can view the doc", but as we're growing the repo, it would be good if any user who decides to make a public ws has this seen by other users, just to encouraging sharing. Admins can already set repos back to private if necessary.

**Comment by filippomc** [comment]
first step: clarify with the name that what we have now is public workspaces

**Comment by filippomc** [comment]
Need some backend adjustments to take into account the difference between public and featured
