### ISSUE TITLE
OSBv2 test deployment

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#13]
Proposal: test.v2.opensourcebrain.org

Deploy on https with letsencrypt

**Comment by filippomc** [comment]
@pgleeson what cluster do we make the deployment of OSBv2? We advise to create a new cluster to use for this and maybe also to test OSBv1

**Comment by pgleeson** [comment]
Sure, sounds good. Maybe give it 2 CPUs as mentioned in the slack..?

**Comment by filippomc** [comment]
yes we can start with two
