### ISSUE TITLE
Clone workspace

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#139]
If a workspace is readonly, show in the workspace page "open as read only"

- in the workspace page, add a button near to edit
- add the clone option in the contextual menu

**Comment by filippomc** [comment]
Error:

{"description": "The dictionary passed to from_dict is not a valid instance of the model schema. The expected schema is {\"type\": \"object\", \"properties\": {\"id\": {\"type\": \"integer\", \"x-generated\": true}, \"name\": {\"type\": \"string\", \"description\": \"Workspace name.\"}, \"description\": {\"type\": \"string\", \"description\": \"Workspace description.\"}, \"timestamp_created\": {\"type\": \"string\", \"format\": \"date-time\", \"description\": \"Date/time the Workspace is created\"}, \"timestamp_updated\": {\"type\": \"string\", \"format\": \"date-time\", \"description\": \"Date/time the Workspace is last updated\"}, \"last_opened_resource_id\": {\"type\": \"integer\", \"description\": \"The workspace resource id the workspace is opened last with\"}, \"thumbnail\": {\"type\": \"string\"}, \"gallery\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"x-de-$ref\": \"WorkspaceImage\"}, \"description\": \"Gallery with images of the workspace\"}, \"user_id\": {\"type\": \"string\", \"description\": \"Workspace keycloak user id, will be automatically be set to the logged in user\"}, \"publicable\": {\"type\": \"boolean\", \"description\": \"Is this a public workspace? Default false\", \"default\": false}, \"featured\": {\"type\": \"boolean\", \"description\": \"Is this a featured workspace? Default false\", \"default\": false}, \"license\": {\"type\": \"string\", \"description\": \"Workspace license\"}, \"collaborators\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"x-de-$ref\": \"WorkspaceCollaborator\"}, \"description\": \"Collaborators who work on the workspace\"}, \"storage\": {\"type\": \"object\", \"x-de-$ref\": \"VolumeStorage\"}, \"tags\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"x-de-$ref\": \"Tag\"}}, \"resources\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"x-de-$ref\": \"WorkspaceResourceEntity\"}, \"description\": \"Resources of the workspace\"}}, \"required\": [\"name\", \"description\"], \"description\": \"Workspace item\"}. The given value is {\"name\": \"Clone of NWB Showcase \", \"tags\": [{\"id\": 2, \"tag\": \"Test\"}, {\"id\": 3, \"tag\": \"NWB\"}], \"user_id\": null, \"thumbnail\": \"workspaces/16/thumbnail.bin\", \"description\": \"NWB examples\", \"publicable\": false, \"featured\": false}.", "type": "MalformedModelDictionaryError", "trace": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/open_alchemy/utility_base.py\", line 124, in construct_from_dict_init\n    facades.jsonschema.validate(instance=kwargs, schema=schema)\n  File \"/usr/local/lib/python3.7/site-packages/jsonschema/validators.py\", line 1022, in validate\n    raise error\njsonschema.exceptions.ValidationError: None is not of type 'string'\n\nFailed validating 'type' in schema['properties']['user_id']:\n    {'description': 'Workspace keycloak user id, will be automatically be '\n                    'set to the logged in user',\n     'type': 'string'}\n\nOn instance['user_id']:\n    None\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 1936, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py\", line 48, in wrapper\n    response = function(request)\n  File \"/usr/local/lib/python3.7/site-packages/connexion/decorators/security.py\", line 327, in wrapper\n    return function(request)\n  File \"/usr/local/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py\", line 144, in wrapper\n    response = function(request)\n  File \"/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py\", line 384, in wrapper\n    return function(request)\n  File \"/usr/local/lib/python3.7/site-packages/connexion/decorators/parameter.py\", line 121, in wrapper\n    return function(**kwargs)\n  File \"/usr/src/app/workspaces/controllers/workspace_controller.py\", line 98, in workspace_clone\n    ws = WorkspaceService().clone(id_)\n  File \"/libraries/cloudharness-common/cloudharness/events/decorators.py\", line 19, in wrapper\n    result = func(self, *args, **kwargs)\n  File \"/usr/src/app/workspaces/service/model_service.py\", line 102, in clone\n    cloned = self.repository.post(cloned, do_post=False)\n  File \"/usr/src/app/workspaces/repository/base_model_repository.py\", line 204, in post\n    new_obj = self.model.from_dict(**body)\n  File \"/usr/local/lib/python3.7/site-packages/open_alchemy/utility_base.py\", line 237, in from_dict\n    init_dict = cls.construct_from_dict_init(**kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/open_alchemy/utility_base.py\", line 127, in construct_from_dict_init\n    \"The dictionary passed to from_dict is not a valid instance of the \"\nopen_alchemy.exceptions.MalformedModelDictionaryError: The dictionary passed to from_dict is not a valid instance of the model schema. The expected schema is {\"type\": \"object\", \"properties\": {\"id\": {\"type\": \"integer\", \"x-generated\": true}, \"name\": {\"type\": \"string\", \"description\": \"Workspace name.\"}, \"description\": {\"type\": \"string\", \"description\": \"Workspace description.\"}, \"timestamp_created\": {\"type\": \"string\", \"format\": \"date-time\", \"description\": \"Date/time the Workspace is created\"}, \"timestamp_updated\": {\"type\": \"string\", \"format\": \"date-time\", \"description\": \"Date/time the Workspace is last updated\"}, \"last_opened_resource_id\": {\"type\": \"integer\", \"description\": \"The workspace resource id the workspace is opened last with\"}, \"thumbnail\": {\"type\": \"string\"}, \"gallery\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"x-de-$ref\": \"WorkspaceImage\"}, \"description\": \"Gallery with images of the workspace\"}, \"user_id\": {\"type\": \"string\", \"description\": \"Workspace keycloak user id, will be automatically be set to the logged in user\"}, \"publicable\": {\"type\": \"boolean\", \"description\": \"Is this a public workspace? Default false\", \"default\": false}, \"featured\": {\"type\": \"boolean\", \"description\": \"Is this a featured workspace? Default false\", \"default\": false}, \"license\": {\"type\": \"string\", \"description\": \"Workspace license\"}, \"collaborators\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"x-de-$ref\": \"WorkspaceCollaborator\"}, \"description\": \"Collaborators who work on the workspace\"}, \"storage\": {\"type\": \"object\", \"x-de-$ref\": \"VolumeStorage\"}, \"tags\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"x-de-$ref\": \"Tag\"}}, \"resources\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"x-de-$ref\": \"WorkspaceResourceEntity\"}, \"description\": \"Resources of the workspace\"}}, \"required\": [\"name\", \"description\"], \"description\": \"Workspace item\"}. The given value is {\"name\": \"Clone of NWB Showcase \", \"tags\": [{\"id\": 2, \"tag\": \"Test\"}, {\"id\": 3, \"tag\": \"NWB\"}], \"user_id\": null, \"thumbnail\": \"workspaces/16/thumbnail.bin\", \"description\": \"NWB examples\", \"publicable\": false, \"featured\": false}.\n"}

**Comment by filippomc** [comment]
To do: add a check to be sure that only workspaces that are visible to the logged in user can be cloned

**Comment by filippomc** [comment]
to do: generate client with openapi

**Comment by filippomc** [comment]
Client api and authorization layer implemented

**Comment by filippomc** [comment]
To be fixed: workspace clone not working when no thumbnail is set

**Comment by sanjayankur31** [comment]
Queries:

- Should the user automatically be taken to the new workspace if it is cloned from the workspace information page? (like when a GitHub repo is forked, the user is taken to their fork?)

- the clone call seems to be a bit slow, do we need to show a timer or something to tell the user that it's happening under the hood (again, like GitHub shows a "your fork is being prepared" page when we fork a repo)?

**Comment by filippomc** [comment]
@sanjayankur31 I don't fully get the first question. The way it's done now is that the workspace is owned by the user doing the clone. 
As for the slowness, I see an about 2 seconds delay and agree we should give a feedback. I propose a spinner (Material ui CircularProgress) on a modal like this one https://geppetto.metacell.us/navigation/loader

**Comment by sanjayankur31** [comment]
Sorry I wasn't clear. For the first question, this is what I mean:

Let's say I go to the workspace page for workspace X:

https://localhost:3000/workspace/95

Here, I clone workspace from the menu, and it creates a new workspace for me, Y.

Should we automatically send the user to the page for workspace Y once it has been created? Currently, there's no feedback to tell the user that the workspace was cloned, and only if they go back to the homepage where their workspaces are listed will they see a "clone of ..." workspace created.

**Comment by sanjayankur31** [comment]
I'll take a look at adding the spinner, thanks.

**Comment by sanjayankur31** [comment]
Note: I don't think we can send the user to the newly cloned workspace at the moment because I don't think the backend call returns the ID of the new workspace

**Comment by sanjayankur31** [comment]
See also: #381

**Comment by filippomc** [comment]
> Should we automatically send the user to the page for workspace Y once it has been created? Currently, there's no feedback to tell the user that the workspace was cloned, and only if they go back to the homepage where their workspaces are listed will they see a "clone of ..." workspace created.

What about a Snackbar message? https://mui.com/components/snackbars/. If we put the link there the user can also go with one click

**Comment by sanjayankur31** [comment]
> > Should we automatically send the user to the page for workspace Y once it has been created? Currently, there's no feedback to tell the user that the workspace was cloned, and only if they go back to the homepage where their workspaces are listed will they see a "clone of ..." workspace created.
> 
> What about a Snackbar message? https://mui.com/components/snackbars/. If we put the link there the user can also go with one click
> 
> > Note: I don't think we can send the user to the newly cloned workspace at the moment because I don't think the backend call returns the ID of the new workspace
> 
> That was intended to happen I will fix that

Great, yeh, then I can add a Snackmessage. That'll work very well. Thanks again.
