### ISSUE TITLE
Wellcome logo on homepage

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#143]
They're paying for it after all...

**Comment by filippomc** [comment]
Do we have some specific requirement from the grant specs? For instance, whether it should be immediately visible, or a modal can also be fine?

**Comment by pgleeson** [comment]
I think it's fine to just add "Supported by" and the Wellcome logo to the Disclaimer box (or under it). Most important thing is that it's visible when someone loads the homepage. 

Longer term, for pages on about/funders/history etc. it's probably best to have a standalone docs.opensourcebrain.org site (like http://docs.neuroml.org), which covers docs/usage for osbv1 and osbv2 as well as non version specific things like project background. We'll set that up from the UCL side...

**Comment by pgleeson** [comment]
@filippomc This would be good to have on the next live release, as we want to start showing it to people soon...

**Comment by filippomc** [comment]
make a bit brighter
