### ISSUE TITLE
Create copy resources workflows backend

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#154]
Principles:
- If a single file is selected in the repository, that single file is copied in the workspace
- If a folder is selected in the repository, all the folder content is copied in the workspace
- if nothing is selected in the repository, the whole repository content is copied in the workspace
- After the copy is done, the workspace content is scanned and osb resources are created for files that are recognized by any of the applications

Sequence diagram:

![OSB-NetPyNE Architecture - OSB2 data loading.png](https://images.zenhubusercontent.com/5c4f23c24557275e4b89d83b/0d124f9d-3e0c-41b2-9e7d-738cc397c3dd)

**Comment by zsinnema** [comment]
add. the "if nothing is selected in the repository, the whole repository content is copied in the workspace" functionality will be implemented by the frontend by sending "/" as the resource root (will be handled like option 2, folder)

**Comment by pgleeson** [comment]
That all sounds great. I assume if multiple files/folders are selected, then the same applieed for each of them individually, they'll individually be retrieved, and then the whole set of files will be scanned for known types?

**Comment by filippomc** [comment]
yes the plan is to scan for files for the whole workspace every time and update the resource list, regardless how the files were imported in the first time
