### ISSUE TITLE
Design featured/public workspaces

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#17]
Design and mockups: make it public on creation? On edit? How the admin can define the public workspaces that go in the home page?

**Comment by tarelli** [comment]
Make them private by default. Have an option to make them public in some workspace settings to mockup. For the second question we could build a UI with two lists one for all workspaces and one for the selected ones. If we have a CMS like this could come from there.

**Comment by filippomc** [comment]
Will do in 2 steps: first every public workspace is also featured
