### ISSUE TITLE
Fixes on resource lists

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#171]
- [x] Long resource list is not scrolling
- [x] Order of resources changes after selection (sort alphabetically)
- [x] Fix resource add not to show the double waiting "fake" resource
- [x] Remove the delete icon from waiting resources
- [x] Long resource list makes nwbexplorer panel expand out of the browser panel so you don't see the python console anymore

**Comment by zsinnema** [comment]
@Muhaddatha the fix for the double waiting is use the import api instead of create workspace resource. the import api will update/delete/create the workspace resource for you. just create a DownloadResource object (see also this pr: https://github.com/OpenSourceBrain/OSBv2/pull/173)

**Comment by Muhaddatha** [comment]
@zsinnema I'm not sure if I am following what you are saying. Was your comment mean for Filippo?
