### ISSUE TITLE
Creating workspaces from repository - some suggestions

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#175]
- [x] When logged out, you can still press Create a workspace, but nothing happens, no warning... @Muhaddatha 
Implementation: remove buttons when the user is not logged in

- [x] When creating a new repository, add it to the top of the displayed list of repos, rather than the bottom (so probably just list the most recent first) @filippomc 

- [x] I assumed when a new workspace is created from a repo, and no files are selected, that it would mean all files were included by default. It might be best to assume this (it's the most natural thing the user would think, give me a workspace with the contents of the repository), or show a dialog stating: "No files from this repository have been selected, and so there will be nothing from this repository in the new workspace. Press OK to proceed, or press Cancel and go back and select some". I recall seeing a "select all" top level checkbox in some demos, but I couldn't see where this was in the interface. @Muhaddatha 
Implementation: the "select all" button will require some design, and the implementation is not straightforward as it's not clear for the user whether it should select only what's visible or everything recursively.

Will go for the dialog, adding all the resources. The message will be "No files from this repository have been selected, and so all the files in the repository will be added in the workspace. Press OK to proceed, or press Cancel and go back and select some"

- [ ] If a text description has been added in the dialog when creating the new repository, this should be shown (and editable ideally) on the "homepage" for the repository, probably above Preview
- [ ] On that note, there's less of a feel like it's a "landing page" for a resource on the repository page. On OSBv1 there's a big title at the top and other info to orient the user, e.g. https://www.opensourcebrain.org/projects/l23dendriticspikes. Maybe have a full width header above Preview/file list with: title, description, link to github, that other elements can be added to later, e.g. tags, user info, etc.
- [x] "Preview" is not really a preview (i.e. a preview of something you will see when a workspace is created..?). It could really just be labelled README

For the 3 above need some graphical design, will do it at a later point.

- [ ] There is an extra 'master' in the path that files are extracted into, e.g. if I select a top level folder `notebooks` to import (from [here](https://github.com/NeuralEnsemble/libNeuroML/tree/master/notebooks)), it goes into /opt/workspace/libNeuroML/master/notebooks. For simplicity for the users it may be best to leave out the master, and probably also the top level repo name.

The path is used because the same resource may come from different repository and different branches. It's useful to have a unique way to reference the resources

That's enough for now... Generally though, it's looking and working great!

cc @filippomc @Muhaddatha

**Comment by pgleeson** [comment]
@filippomc @Muhaddatha Regarding the first point above, it would be better in general if buttons like this stay in place (and give a warning when pressed that you need to be logged in) rather than are taken away when the user is logged out. We want potential users to be able to see what they can do if they were to sign up/log in...

Regarding repo homepage restructuring, that's fine regarding needing to redesign it, but could you for now juts change "Preview" to "README from GitHub:"

**Comment by filippomc** [comment]
@pgleeson we may replicate the behaviour in the home page with the modal that asks the user to login. 

As for changing the "preview" name, we want to use that place also for future repositories coming from other sources like Dandi and Figshare, so it would be nice to have a more generic name (like "description"?).

**Comment by pgleeson** [comment]
@filippomc Ok, great re the modal warning. 

Fine to change Preview to Overview for now.
