### ISSUE TITLE
What to do with html in markdown?

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#177]
For now, it's being escaped. I wouldn't suggest to show it as it may dangerously break down pages. 
Probably we should hide all html code? In this case better also change the way that images are included, like the image below (see markdown):

Example:
![image.png](https://images.zenhubusercontent.com/5c4f23c24557275e4b89d83b/802ca300-a02b-4677-bd59-1f5d3d259029)

**Comment by pgleeson** [comment]
Are there not standard packages which can be used for converting (github flavoured) markdown to valid html? Wouldn't it be best just to use one of these?

**Comment by filippomc** [comment]
The library we are using (ReactMarkdown) supports html, we just need to decide whether we want to allow this html to potentially break the page (and configure it to be safe, see [here](https://github.com/remarkjs/react-markdown#appendix-a-html-in-markdown)). I don't see the same danger if we include markdown syntax enhancements, but that's something to tacke specifically on case by case.

**Comment by pgleeson** [comment]
Personally I think as this is mainly for showing Github readmes at the moment, make it as close to the gh functionality, so allow html. better to have most readmes showing and wait until soemthing breaks it rather than disable features we know some people use.
