### ISSUE TITLE
Images/thumbnail for workspace broken?

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#178]
Tested on v2dev, one was adding an image at time of creation of workspace, one is adding image afterwards.
<img width="654" alt="Screenshot 2021-05-27 at 09 50 43" src="https://user-images.githubusercontent.com/1556687/119796255-213cb100-bed1-11eb-8fd5-2bf56d03d6e6.png">

**Comment by filippomc** [comment]
Yes this is a known regression, thanks for creating the issue anyway!
