### ISSUE TITLE
Email notifications for new registered users

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#187]
info@opensourcebrain.org

**Comment by filippomc** [comment]
Didn't found any out of the box solution available, need to write some code (see also https://lists.jboss.org/pipermail/keycloak-user/2018-November/016387.html).

**Comment by filippomc** [comment]
@pgleeson Keycloak does not have embedded the mail to the adminstrators, while it has the email verification for new subscriptions. Implementing that will save us some time and will help us avoid random subscriptions in a good way. Leaving this for the next sprint

**Comment by pgleeson** [comment]
> @pgleeson Keycloak does not have embedded the mail to the adminstrators, while it has the email verification for new subscriptions. Implementing that will save us some time and will help us avoid random subscriptions in a good way. Leaving this for the next sprint

Ok, that's a good solution for now.

**Comment by zsinnema** [comment]
I've enabled email verification in the osb2 realm and configured the smtp server
![image.png](https://images.zenhubusercontent.com/5e2079d495a332382cd766a5/4e6d93b6-ab00-4c4e-97dd-b8717355d439)

![image.png](https://images.zenhubusercontent.com/5e2079d495a332382cd766a5/d1c11c68-ffa6-4c72-a8b1-ea238ddee278)

![image.png](https://images.zenhubusercontent.com/5e2079d495a332382cd766a5/172a42e4-d64f-487d-87a9-d458332dde4e)

![image.png](https://images.zenhubusercontent.com/5e2079d495a332382cd766a5/278c50ff-8f5a-471b-b576-f24879368b4c)
