### ISSUE TITLE
Release to v2

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#196]
The core functionality of v2dev is much more advanced than what's currently at v2, and it would be good to get this live on v2, so the repositories feature can be tested on a more stable system. Would it be possible to make a quick release on v2 @filippomc? Would this wipe the current workspaces?

**Comment by filippomc** [comment]
Yes that will wipe out current workspaces and repositories, unless we create some migration system for the database (it will take some more time than recreating the workspaces but will be beneficial also for the future)

**Comment by pgleeson** [comment]
@filippomc Will that be every time or just following the major move to repos? So can we do a wiping update now and make one more update before CNS that won't wipe anything?

This is of course related to backup/restore functionality, which will be essential once we have live users...

**Comment by filippomc** [comment]
We can certainly proceed as you suggest. DB wiping won't be required for every update, only the ones that change the database structure. Worth noticing that also seamlessly irrelevant updates may require the db to be updated, one being sorting repositories by update date (we were not storing update date before).

**Comment by filippomc** [comment]
proceed with wiping out everything
