### ISSUE TITLE
NetPyNE application doesn't load on v2dev

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#198]
A workspace previously opened with jupyterlab, when opened with NetPyNE will fail with error below.
A new NetPyNE workspace will try to open in Netpyne, fail (similar error), then automatically be opened in jupyterlab
<img width="1203" alt="Screenshot 2021-06-16 at 10 26 20" src="https://user-images.githubusercontent.com/1556687/122194400-506d8f00-ce8d-11eb-81b9-9c4deed65ba6.png">

**Comment by filippomc** [comment]
Since netpyne and nwb explorer have long deployment time, we take sometimes the deployment leaner by removing them on dev.

**Comment by pgleeson** [comment]
This issue is still kind of happening... I loaded a netpyne workspace on v2dev, it loaded netpyne-ui and I started creating a model, then it automatically refeshed and went to jupyterlab...

**Comment by filippomc** [comment]
That's another issue I guess. Did it occurred that it switched to jupyterlab as soon as a new resource was imported?

**Comment by pgleeson** [comment]
Fixed now I belive
