### ISSUE TITLE
Pre release 0.3.0 fixes

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#199]
This card is a catchall for all bugs, stability  and ui fixes that are needed before the release 0.3.0

- [x] opening other people private repos with admin does not work
- [x] text on Azure buttons not visible on hover
- [x] On a repository, after clicking 'add to existing workspace' the modal should give the options to go directly to the workspace.
- [x] Unnecessary vertical scrolling happening one the code snippets inside the repository overview. This only happens on larger screens.
- [x] Navigation menu items are hidden behind an open workspace drawer.
- [x] Bottom of repositories list is hidden on larger screens.
- [x] Small spacing issue with button next to overview in repository page.
- [x] Bottom of workspace card list in home page hidden on larger screens.
- [x] Repositories page not scrolling down.
- [x] workspaces tab look does not match the design.
- [x] Remove icon from blocked accordion in drawer.
- [x] Menu in the workspace drawer should be the same when reduced.
- [x] When clicking on a resource in the drawer, the application associated with that resource should open.
- [ ] Change from dark to light theme inside JupyterLab no longer works.
- [x] Remove "My account" and "Settings" from menu dropdown on user name on top right
- [x] Remove spinner from workspace resources after adding a new resource.
- [x] sort resources list alphabetically.
- [x]  when a new resource is added, if no other resource was selected, the application may switch to a different one unexpectedly
- [x] If a user tries to add a repository for the second time in a row, the previous repository information is saved in the dialog and an infinite spinner is displayed. This happens in the repositories page.
- [x] Is the user deletes a selected/open source in the workspace page and doesn't select another one, the workspace cannot be accessed.

**Comment by pgleeson** [comment]
FYI added 2 more items to bottom of list...
