### ISSUE TITLE
Strange behaviour: copying state/resources from previous workspaces...

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#205]
I created a brand new workspace from a repo (NeuroML documentation 2) and opened it:
<img width="1674" alt="Screenshot 2021-06-18 at 11 05 16" src="https://user-images.githubusercontent.com/1556687/122545123-6615bc80-d025-11eb-941f-d99b724b293b.png">
- Even though type was Modelling it initially opened in NWBExplorer, then reloaded in jupyter
- While the resources for NeuroML documentation 2 is there, there is also one from TestNetPyNE that I didn't add
- The state was clearly from the previous session (taken from the lab-a511.jupyterlab-workspace file I believe), with the png file open, pointing to a file in TestNetPyNE

**Comment by filippomc** [comment]
Volumes are named workspace-[workspaceid]. Since we are not deleting old volumes when making new deployment on dev, old workspace volumes can be reused on old deployments. We are making sure this does not happen in the live deployment.

**Comment by pgleeson** [comment]
Will repoen if I notice again
