### ISSUE TITLE
Create workspace from repository in the homepage

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#219]
Add an icon to the "Create a new Workspace" box in the homepage.

The text is "From repository", subtext is "any" (temporary).
The icon is to be chosen.

This will open a modal similarly to the copy resource from repository functionality inside a workspace
1. Choose repository
2. choose files
3. edit new workspace

**Comment by pgleeson** [comment]
Looks good. Some minor tweaks. 
- [ ] Move this to the 4th entry in that panel, i.e. atfer netpyne, nwbe, etc.
- [ ] Change top text to "Workspace from repository", bottom text to "Any application"
- [ ] If possible, add a button on the first dialog "Explore all repositories" which closes this dialog and loads the main repository view page.

**Comment by filippomc** [comment]
@pgleeson what about having some text with a link instead of the button? 
Something like: "You don't find the repository you're looking for and create a new repository or just want to explore the OSB repositories? Go [here](#)"

**Comment by pgleeson** [comment]
@filippomc Sure text and a link is fine, maybe: "If you can't find what you're looking for, go [here](https://www.v2.opensourcebrain.org/repositories) to explore all the OSB repositories, or add a new one."
