### ISSUE TITLE
Add button to the main banner for the repositories page

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#236]
@pgleeson can you please suggest the wording for the banner? (Keep in mind that the banner changes when logged in)

**Comment by pgleeson** [comment]
Probably just add 2 buttons beside "Sign up": "View Repositories" "More information", with the last one linking to https://docs.opensourcebrain.org/OSBv2/Overview.html in a new tab. These 2 buttons can be kept once the user is logged in
