### ISSUE TITLE
Implement featured vs public workspaces backend

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#241]
Add a boolean type to the Workspace type indicating that the workspace is featured.
Add also to repositories.

Constraints:
 - Only the administrator can make a workspace featured

When searching for featured workspaces, check also user access

**Comment by zsinnema** [comment]
to add the featured column to the database execute these commands:
```
kubectl -n <namespace> exec deployment/workspaces-postgres-host -ti -- bash
psql -U workspace -h localhost workspaces
alter table workspace add column featured boolean not null default false;
\q
exit
```

**Comment by zsinnema** [comment]
todo: impl only admin can (un)set featured
