### ISSUE TITLE
Design user page

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#276]
The user page is part of the application

Show:
- basic user info
- user groups info
- user quota info

- [ ] Wireframes
- [ ] Mockups (will see after the wireframes whether this is needed)

**Comment by pgleeson** [comment]
Can be inspired by the (nice and simple) design for OSBv1 userpages: https://www.opensourcebrain.org/users/4/.

All that info on the left will eventually be transferred to OSBv2 as attributes (key/value pairs) taken from the user's keycloak profile.
