### ISSUE TITLE
Workspaces opened in NWBE should select an NWB file randomly and open that, if none have prev been opened

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#300]
- [x] Workspaces opened in NWB explorer don't open one of the nwb file resources by default, just the NWBE homepage
- [x] Link in ... menu of individual workspaces on homepage for "Open workspace" is broken, goes to https://v2dev.opensourcebrain.org/workspace/open/14 etc.

**Comment by pgleeson** [comment]
Renaming for clarity

**Comment by filippomc** [comment]
Did a radical refactoring of how osb communicates with the application. Now the flow is more consistent and ready to handle applications creating resources https://github.com/OpenSourceBrain/OSBv2/blob/release/0.5.4/docs/osb-applications-protocol.md

**Comment by filippomc** [comment]
fix: not opening with the correct application after explicit open

**Comment by pgleeson** [comment]
Fixed, but some other strange behaviour I've noticed that I'll open other issues for...
