### ISSUE TITLE
Clicking on a notebook resource should open it in Jupyterlab application

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#302]
When a list of notebook resources is shown in Jupyterlab, the most natural thing to happen when one is clicked on is the notebook opens in the existing Jupyterlab application. Currently nothing happens when you click.

**Comment by filippomc** [comment]
This can take some time as we need to interact with jupyterlab apis to open the required resource

**Comment by pgleeson** [comment]
Renaming...

**Comment by pgleeson** [comment]
Moving from milestone and adding RELEASE label...

**Comment by filippomc** [comment]
differently from nwb explorer, don't want to open a random resource if noone was selected

**Comment by filippomc** [comment]
differently from nwb explorer, don't want to open a random resource if noone was selected

**Comment by pgleeson** [comment]
Working on live
