### ISSUE TITLE
How to run netpyne ui from dockerfile?

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#305]
@filippomc I can locally build the netpyne-ui instance as described in https://github.com/OpenSourceBrain/OSBv2/blob/develop/applications/netpyne/Dockerfile and used by osbv2 using:

     docker build -t mynetpyneosb -f Dockerfile .

but how can I run this in a container to test it locally? I tried: 

    docker run -p 8888:8888  --name mynp mynetpyneosb

but http://localhost:8888/geppetto keeps spinning and coming up with "Reloading Python Kernel"

**Comment by filippomc** [comment]
Hi Padraig, there is a configuration on osb that sets the websocket on tls. Please try remove this line to try locally: https://github.com/OpenSourceBrain/OSBv2/blob/develop/applications/netpyne/Dockerfile#L9

**Comment by pgleeson** [comment]
Perfect, thanks! Much easier to test locally now
