### ISSUE TITLE
Show "Create new workspace" button when not logged in

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#309]
Currently the create new workspace button is absent when a user is not logged in. 

However it would be good for a casual/browsing user to be able to see it and understand the overall workflow, and maybe be allowed to press the button, but get a warning that they need to be logged in to create a new one. I think this was the previous behaviour.

**Comment by filippomc** [comment]
This is in the repository page, right?

**Comment by pgleeson** [comment]
Yes, it would be great if the 2 buttons were shown on the repo page as they are currently on live

<img width="1680" alt="Screenshot 2021-11-30 at 18 07 44" src="https://user-images.githubusercontent.com/1556687/144103379-7661eb8c-8c7e-440c-b0d3-3e426810b1a1.png">

**Comment by filippomc** [comment]
fixed
