### ISSUE TITLE
Fix new workspace from repository

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#316]
After saving, the modal does not close, but the workspace gets created anyway

**Comment by sanjayankur31** [comment]
Tried this on v2dev now (~1605 UTC on Fri 27 Jan). The modal didn't go away, but the workspace doesn't show up in the list in the homepage either. Is it only being created in the backend?

**Comment by sanjayankur31** [comment]
I got an e-mail about the workspace creation, so yes, it looks like it was created in the backend `workspace - 70`
