### ISSUE TITLE
"Open workspace" is ambiguous in menu of an already opened workspace

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#319]
Maybe remove and just have "Open with..." for a specified application?

<img width="667" alt="Screenshot 2021-12-16 at 10 27 44" src="https://user-images.githubusercontent.com/1556687/146354707-24bfdffa-b784-4b39-ac0a-93a67eef7ec2.png">

**Comment by sanjayankur31** [comment]
This pop up is shared between the workspace cards and here, and that's why it has an "open" option here too. We should be able to remove it from the workspace page only if that's what we want to do here.

**Comment by filippomc** [comment]
Yes the component is shared, can add a condition to remove that option when we are inside the workspace
