### ISSUE TITLE
New repositories and workspaces - dialog doesn't close & resources not added

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#320]
When adding a new repo or creating a workspace, the respective dialogs don't close, just have a spinning circle, but the repo/ws is created in the background...

On v2 live...

**Comment by pgleeson** [comment]
Updated title to point out resources don't get added to new workspaces...

**Comment by filippomc** [comment]
this was related to a notification system configuration which is not taken automatically. Fixed and creating a more specific issue about this.

**Comment by filippomc** [comment]
Seems more a cloud-harness issue actually https://github.com/MetaCell/cloud-harness/issues/360
