### ISSUE TITLE
Improve formatting of thumbnail images on workspace homepages

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#322]
e.g. https://www.v2.opensourcebrain.org/workspace/4

<img width="1087" alt="Screenshot 2022-01-05 at 12 58 49" src="https://user-images.githubusercontent.com/1556687/148221516-2c62e7d5-dced-482e-be45-a44ee19ada3e.png">

**Comment by sanjayankur31** [comment]
I guess we could use an Avatar both at the front page and on the workspace page? How do these look @pgleeson ?

![osb-ws-avatar4](https://user-images.githubusercontent.com/102575/149975933-612b6004-2fcd-4317-946b-99203d12c4a9.png)
![osb-ws-avatar2](https://user-images.githubusercontent.com/102575/149975937-60009ccc-47a0-44f7-b26a-75c01ffb0aa9.png)
![osb-ws-avatar-1](https://user-images.githubusercontent.com/102575/149975940-966a73e5-a7e8-484b-b965-34d3d6838d3c.png)


If the avatar on top looks OK, we can remove the image from the main bit?

**Comment by sanjayankur31** [comment]
And using the avatar in the workspace list would make it look like this (sort of uniform?)

![osb-workspace-list](https://user-images.githubusercontent.com/102575/149985322-3a3cafc6-34b6-41a5-9ec8-5ac8cd1c9697.png)


There are different options to fallback to if no icon is found:

https://v4.mui.com/components/avatars/#fallbacks

Here, I've made it fallback to the name of the workspace, but it could also just be the first letter or another icon etc.

**Comment by filippomc** [comment]
I suggest to stick to the initial design as the avatar idea introduces another level of complexity, making even more difficult to find the right image and center it. The more the variants to support, the more the need for custom cuts of the image. The general principle should be to choose a default ratio ~2/1 cut and stick to it everywhere, with the initial thunbnail preview giving the right idea of what cut to expect everywhere the image is displayed

**Comment by sanjayankur31** [comment]
Yeh, sounds good. We had a look and decided to stick with the original
rectangular shape too. I'm tinkering with bits and will open a PR when i
have something we're happy with 👍
