### ISSUE TITLE
Repository list: change "view in github/dandi" button to "create new workspace"/"add to workspace"

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/OSBv2#333]
the big "view in github" button in the repository list makes the user think that this is the next step from this page, but for us the next step is to create a workspace from the repository (or add something from the repo to a pre-existing workspace). So, the importance of "view in github" needs to be reduced, and the workspace based flow needs to be emphasized.

Maybe the "open in github/dandi" button can be replaced by an icon in the first column of the list, just to indicate to the user what the source of the repository is, and the button made something related to the workspace flow?

**Comment by pgleeson** [comment]
No longer relevant
