### ISSUE TITLE
Repositories: can they be updated?

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/OSBv2#334]
once we've created a repository, can it be updated? (should it? how?)

**Comment by filippomc** [comment]
Yes it can be updated by the owner of the repository or by an admin user.
![image](https://user-images.githubusercontent.com/46561561/150791331-a123fbb6-dc3f-4662-83f3-a65733531606.png)
![image](https://user-images.githubusercontent.com/46561561/150791420-43598858-a4ff-4fde-a042-96d333611026.png)

**Comment by sanjayankur31** [comment]
Thanks Filippo. Is this on live or on dev? When I click the three dots, the menu only shows "edit". What should the user do there?
![v2-workspace-edit](https://user-images.githubusercontent.com/102575/150801286-4c6aefcc-9341-4286-995f-52fd4af19102.png)

(I think I broke v2dev, so I'll check there once it's back up)

**Comment by filippomc** [comment]
v2dev back live. Once clicking on edit the edit modal should appear

**Comment by sanjayankur31** [comment]
OK, that works. What does one do to update the repo then?

**Comment by sanjayankur31** [comment]
Wait, I'm being stupid. I was wondering if the commit that the repo was imported from can be updated, but in fact, whenever we look at the repo, it always shows the latest commit on the given branch. So, git wise, it is always up to date.

Closing this, sorry for the stupidity!

**Comment by filippomc** [comment]
Well there may be something to improve in the design or clarify someway. if that wasn't clear to you, that won't certainly be clear to the average user!

**Comment by sanjayankur31** [comment]
Yeh, I guess "last updated .." to me means that the creator last updated it on that time, manually. This then makes one think that they are "static" and the creator updates them from time to time. It doesn't say "the repository was updated at the source at this time, and this is what we are showing you".

I'll file a ticket for this so we can discuss it.
