### ISSUE TITLE
Repository list page: filter value does not remain in tag filter text box

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/OSBv2#340]
On v2dev: I set "neuroml" as the tag filter text box, and hit enter. That updated the list as expected. But, when I go back to the filter box, the tag text no longer has "neuroml" in it. It should remain there.

**Comment by filippomc** [comment]
Moving the filter value to the redux store would solve the issue

**Comment by sanjayankur31** [comment]
Didn't need to move to the store in the end, @filippomc . PR opened. Seems to work as expected, but could you check if it's the right way to do this?
