### ISSUE TITLE
Note licenses for v2

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/OSBv2#354]
We don't seem to have noted the licenses of the different OSB components anywhere, so it is not currently clear how FOSS v2 is. We should

- check that all components have FOSS licenses (and select licenses where they have not been explicitly listed)
- note the license breakdown in a file
- include license texts where required, since some licenses require the license text to be included in the source code

(This is important from a FOSS perspective, and it's also important from our funding perspective etc.)

**Comment by pgleeson** [comment]
Agreed, at the very least for this repo... @tarelli @filippomc I assume it should be standard MIT license?

**Comment by pgleeson** [comment]
Agreed to be MIT license...

**Comment by sanjayankur31** [comment]
Once #510 is merged, next task:

- [ ] update "about dialog" to list license and link to license text.
