### ISSUE TITLE
Improve tags filters functionality on repositories

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#360]

**Comment by sanjayankur31** [comment]
current design idea is to merge the functions of the filter component into the text search component:

- only use one search box for all searches
- when the user types in something, show matching tags in drop down list and allow user to select these tags
- if user does not select tag, use text search
- if user selects tag, use tag search
- include modelling/experimental/general in drop down list also (either as tags, or in a different section?)

**Comment by filippomc** [comment]
@sanjayankur31 sorry I created 2 duplicate issues by mistake, see also #359

**Comment by filippomc** [comment]
Closing as duplicate. Copying the notes to #359
