### ISSUE TITLE
All users presented as owners of all repositories on their user page

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#372]
e.g. this test user being told they own all the 28 repos created to date (shown on left too)

<img width="1243" alt="Screenshot 2022-02-23 at 09 33 48" src="https://user-images.githubusercontent.com/1556687/155293207-ead725e3-75cd-4069-832a-45de32fb4755.png">

**Comment by filippomc** [comment]
Need to add filter in the backend

**Comment by pgleeson** [comment]
Still an issue...

**Comment by pgleeson** [comment]
Fixed
