### ISSUE TITLE
DANDI repositories - title, description and tags no longer automatically pulled/added when adding repository 

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#379]

**Comment by pgleeson** [comment]
Reopening as it doesn't seem to work anymore...

**Comment by sanjayankur31** [comment]
Is this on v2 live @pgleeson ? I just tried it on v2dev and it seems to work. The title isn't pulled in (is it meant to be?) but the branches and tags seem fine when I try to add this one:

https://dandiarchive.org/dandiset/000053/draft

![image](https://user-images.githubusercontent.com/102575/181002935-3044472a-e007-4180-b05a-585915f1d29d.png)

Could you note what dandi repo you tried with?

**Comment by filippomc** [comment]
Note that some dandi repos don't have tags

**Comment by filippomc** [comment]
Not working for https://dandiarchive.org/dandiset/000231

**Comment by filippomc** [comment]
Implementation for name and description required

**Comment by filippomc** [comment]
fill default: experimental for Dandi

**Comment by pgleeson** [comment]
Fixed
