### ISSUE TITLE
Files not getting copied to new volume on clone

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#381]
All files present on the volume of a workspace which is cloned should appear on the volume of the new workspace. This is not happening, even though the resources show up as being present:

<img width="872" alt="Screenshot 2022-02-25 at 14 41 40" src="https://user-images.githubusercontent.com/1556687/155734439-d19fb16d-9aeb-4d9c-8a5c-70ef025b36bc.png">

**Comment by filippomc** [comment]
Needed to add the "Compute Engine persistent disk CSI Driver" to the cluster

**Comment by filippomc** [comment]
Actually the above is not enough as the CSI driver must be used in the full volume provisioning chain by a dedicated storage class

**Comment by filippomc** [comment]
fixed
