### ISSUE TITLE
Clicking on OpenSourceBrain logo signs you out?

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#387]
Reported by @salvadord: When you click on “OpenSourceBrain” top-right to go back to the list of workspaces, it signs out of your user and need to sign back in

I tried this a few times, it signed me out once (the session may have expired), but I couldn't reproduce it. Something to watch out for...

**Comment by sanjayankur31** [comment]
Not been able to reproduce this yet. Let's leave it open for the time being, and I'll keep trying to reproduce this. 

The login could just timeout I guess.

**Comment by salvadord** [comment]
for me it's happened several times... can the session expire while you are working in a workspace? (I assume it shouldn't)

**Comment by pgleeson** [comment]
@salvadord How exactly are you using it? Are you using it as a way to leave/close a workspace and go back to the home page in the same tab, or right clicking and selecting "Open link in new tab"?

Does it also happen if you open osbv2 in a private browsing window  and log in there (to avoid any issue with cache)?

**Comment by sanjayankur31** [comment]
Seems to happen when using a private window from the looks of it. Will need some more investigation.

**Comment by salvadord** [comment]
fyi I wasn't using one

**Comment by salvadord** [comment]
@pgleeson I was using it as a way to leave/close a workspace and go back to the home in the same tab. I tried to reproduce now quickly but it didn't happen, so I suspect it might be related to going back home after a long period of time.

**Comment by pgleeson** [comment]
Closing as nothing like this has happened/been reported for a while.
