### ISSUE TITLE
Add support for FigShare as repository source

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#390]
To access file son Figshare (e.g. https://figshare.com/articles/dataset/19298747) as well as the UCL data repository (e.g. https://rdr.ucl.ac.uk/articles/dataset/Data_and_code_for_Figures_for_the_article_Real-time_3D_movement_correction_for_two-photon_imaging_in_behaving_animals_/11949063)

Some work has been done on this already, e.g. 
https://github.com/OpenSourceBrain/OSBv2/blob/develop/applications/osb-portal/src/apiclient/workspaces/models/FigshareRepositoryResource.ts
https://github.com/OpenSourceBrain/OSBv2/blob/develop/applications/workspaces/server/workspaces/service/osbrepository/adapters/figshareadapter.py

How much of this is placeholder code and how much further development would be required @zsinnema?

**Comment by filippomc** [comment]
That's placeholder code. For the development estimates please refer to the user stories REPO_CREATE_FIGSHARE and REPO_INFO_FIGSHARE

**Comment by pgleeson** [comment]
Done!
