### ISSUE TITLE
As a user/admin I want to see a list of all users on the platform with some information on them

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/OSBv2#411]
This is useful for developing the community around OSBv2, and also for us to be able to easily see usage.

features:

- admins see some extra information, like when the user was last logged in
- non-admins see all public information from users' profiles

**Comment by filippomc** [comment]
As for the admin, users list and login events are available on the keycloak admin dashboard once configured. For any more advanced kind of tracking I recommend to use a proper tracker like Google Analytics. If we don't like Google Analytics for any reason (cross-site tracking may be one reason) there are also open source alternatives like Piwik.

**Comment by sanjayankur31** [comment]
WIP here: will open a PR when ready enough for review (and tweaks):

https://github.com/OpenSourceBrain/OSBv2/tree/feat/add-user-list-backoffice
