### ISSUE TITLE
Workspace filtering: clicking the search icon to clear the search clears the value of the search field but does not reset the workspace lists

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/OSBv2#420]
Reproduce:

- search for something, like "bria"
- see list get filtered
- click on search icon to remove search
- list is not reset
- click again on search icon
- no "bria" text in the search there

So the search value has been cleared but the list has not---still suggests that a filter for "bria" is in place.

**Comment by filippomc** [comment]
Good catch: should not reset the search IMO

**Comment by filippomc** [comment]
fixed by disallowing the toggle when a search is on
