### ISSUE TITLE
Dialog for Edit workspace can't be closed/cancelled & wrong title

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#422]
Dialog actions for Cancel and close window are broken when dialog is opened to Edit the workspace (not when creating a new one though).
Also title of dialog should be changed to Edit workspace.
<img width="978" alt="Screenshot 2022-03-24 at 11 03 11" src="https://user-images.githubusercontent.com/1556687/159903105-1e3d2923-83cd-49a2-b600-6c264d5fbb32.png">

**Comment by sanjayankur31** [comment]
Looks like a regression from the dialog changes, looking into it now.
