### ISSUE TITLE
Removing file from workspace

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [OpenSourceBrain/OSBv2#428]
When pressing the trash icon next to a specific file of a workspace

<img width="1038" alt="Screenshot at Mar 30 12-05-54" src="https://user-images.githubusercontent.com/99416933/160820743-706211ff-592f-43b7-9443-69b6778d3b23.png">

 it does not get removed from the workspace (even after reloading the page)

<img width="1310" alt="Screenshot at Mar 30 12-08-10" src="https://user-images.githubusercontent.com/99416933/160821196-e2480010-a2bb-4487-9172-8ad8c134e7ad.png">
<img width="1323" alt="Screenshot at Mar 30 12-07-32" src="https://user-images.githubusercontent.com/99416933/160821213-3a3367b5-3df2-4406-a90c-fde8ce28f7d7.png">

**Comment by sanjayankur31** [comment]
Thanks for the report, is this on the live instance or the dev instance please?

**Comment by filippomc** [comment]
Looking into that

**Comment by filippomc** [comment]
fixed
