### ISSUE TITLE
Loading spinner after editing a workspace never disappears

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [OpenSourceBrain/OSBv2#429]
When editing a workspace

<img width="1410" alt="Screenshot at Mar 30 12-11-25" src="https://user-images.githubusercontent.com/99416933/160821938-320eba45-54af-45f1-9059-9bfa051c688d.png">

 the information edited 

<img width="1375" alt="Screenshot at Mar 30 12-11-49" src="https://user-images.githubusercontent.com/99416933/160821954-edcecc64-753f-497e-ad1d-1463d29fafa1.png">

appears correctly but the loading spinner never disappears

<img width="1417" alt="Screenshot at Mar 30 12-12-36" src="https://user-images.githubusercontent.com/99416933/160821975-7cd63a2e-8570-427a-a1e4-cb5c01726bc6.png">

Only after reloading the page

<img width="1419" alt="Screenshot at Mar 30 12-13-47" src="https://user-images.githubusercontent.com/99416933/160822024-4f878639-d815-4956-a1dc-f8e9b666a959.png">

**Comment by SimaoBolota-MetaCell** [comment]
Thank you for adding the labels @sanjayankur31

**Comment by sanjayankur31** [comment]
I can reproduce this, and I think I know why it happens. Will open a PR with fix now. Cheers.
