### ISSUE TITLE
Add confirmation option when deleting a repository

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#435]
Currently it's not possible to delete an existing repository. A user should at least be able to delete their own repositories.

This may cause issues down the line though if there is a link back to the original repo from a workspace created from it, but a more frequent use case is users may just want to clean up prevously added repos which are no longer relevant/added by mistake, and don't want them to show up in searches. 

Another option might be to just flag these as "deleted", and not show them in the main repo list, but leave them in place so that links will still work...

**Comment by pgleeson** [comment]
This works, but ideally a conf dialog should be shown in case of accidental deletion - title updated to reflect this

**Comment by filippomc** [comment]
the edit and delete option should be available only to the owner or administrator

**Comment by pgleeson** [comment]
Works on live
