### ISSUE TITLE
Test latest dev of netpyne

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#450]
- [x] Create branch with changes from osb and netpyne-ui development branch
- [x] Try on v2dev

**Comment by filippomc** [comment]
@pgleeson branch osb2-dev created in the netpyne-ui repo. To install run `python utilities/install.py --geppetto feature/netpyne_migration --netpyne 1.0.0.2 --dev` (may need to run twice). 
This version is still preliminary as there is no release candidate on netpyne, but should be enough to start testing the experiments feature. Will follow up when there is something nearly stable

**Comment by filippomc** [comment]
@pgleeson to try the netpyne image locally (or in a github actions) can run the following commands from OSBv2 rot:
```
harness-deployment cloud-harness . -i netpyne
skaffold build
```

to install harness-deployment and skaffold please refer to the main readme

**Comment by pgleeson** [comment]
Done!
