### ISSUE TITLE
Add name of owner in tooltip when viewing all workspaces

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#457]
To ease searching through multiple workspaces (which could all have the same title/metadata) it would be good if the name of the user who created it was displayed in a tooltip, e.g. when hovering over the workspace name

<img width="309" alt="Screenshot 2022-04-20 at 12 15 32" src="https://user-images.githubusercontent.com/1556687/164219206-ba62f0c8-ac58-47a9-9cb8-93877b784b4f.png">

**Comment by sanjayankur31** [comment]
I think we're better off showing the name of the owner here, not just as a tooltip. Having to hover over multiple entries to find the right workspace will not be a good user experience, especially if there are lots of workspaces with similar names (very likely when folks do tutorials!).

So, I'd suggest we put the name of the creator right there below the name of the workspace.

In general, I'm not a fan of using tooltips to show information that should be obviously visible:

- it isn't obvious that a tooltip exists unless we put an icon there to inform the user
- users have to move around quite a bit depending on how the cards are organised etc, so it could be tedious
- tooltips are not as accessible---users relying on screenreaders etc. will find it hard to access them

So where we think a tooltip is needed, I think we need to first see if the information to be shown is important or optional. If it isn't optional (like an extra note), we shouldn't use a tool tip---we should update our design to make the info easily visible.

**Comment by pgleeson** [comment]
Sure, happy for the name to be displayed if there's room. Maybe at the bottom in the smaller font of the Jupyterlab etc.

**Comment by pgleeson** [comment]
Name shown in workspace now...
