### ISSUE TITLE
Should username be editable?

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#464]
In the Edit my profile dialog, you can change your username. Is this by design? I know the long keycloak id is the unique key, but is there anywhere else a changed username will cause issues?

**Comment by sanjayankur31** [comment]
Changing usernames is quite a can of worms. For example---if I change my username, does that mean someone else can then use my previous one or should it be blocked for some time. It can be done, but it isn't as simple as just changing an entry in the db---it'll require a lot more thought.

This was also discussed in the Fedora community for their new auth system, so you can see the discussion here (they use IPA as their backend etc. but the general issues are the same):

https://github.com/fedora-infra/noggin/issues/105

**Comment by filippomc** [comment]
Should we disallow username change?

**Comment by sanjayankur31** [comment]
Probably the best thing to do for the moment. We can revisit this later if we get requests from users to change usernames?

**Comment by filippomc** [comment]
I'm for disallowing the change for now too as I don't really it as a feature worth supporting. As Padraig points out is not a relationship key so shouldn't be troublesome in general, but we may need to check some edge cases where the username may be cached in the frontend

**Comment by sanjayankur31** [comment]
> Need also to fix the email as it is not shown in the form and be editable.

Was looking into this. The `client.get_current_user()` call here is always throwing a "404: user not found" exception here, so the e-mail is always cleared in the except block, even when I'm logged in.

https://github.com/OpenSourceBrain/OSBv2/blob/develop/applications/accounts-api/backend/accounts_api/services/user_service.py#L27

I looked at the cloudharness code, and it looks like an authentication_token is necessary for the user look up? If no token is provided, it returns `-1` as a userid. Does this mean that to do the check and strip out the e-mail here, we need to also make this call a private one that requires authentication?

https://github.com/MetaCell/cloud-harness/blob/324ea0f0978fe31a1dcd21ee3138b9df230a3f29/libraries/cloudharness-common/cloudharness/auth/keycloak.py#L92

**Comment by pgleeson** [comment]
Username not editable now
