### ISSUE TITLE
Fix My account link

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#483]
The my account link does not work from other's user account pages

**Comment by sanjayankur31** [comment]
@filippomc : the URL is changing to the new one, so "history.push" is working, but the page isn't being redirected to the new URL

I see some posts about syncing versions of the history and react-router etc. node modules, but I think it's best if you take a look at this?

https://github.com/remix-run/react-router/issues/7415

**Comment by filippomc** [comment]
> [remix-run/react-router#7415](https://github.com/remix-run/react-router/issues/7415)

They mention the issue being using history 5.x while history is 4.x in our package-lock. Must be something else

**Comment by filippomc** [comment]
The issue is in the way that the user object state is refreshed in the component. Opening a pr.
