### ISSUE TITLE
"All repositories" on repos page is actually "Back to last page"

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#486]
Clicking on All repositories when a single repo page is shown actually results in going back to the last page (which in many cases is the list of all repos...), e.g. go to https://v2dev.opensourcebrain.org/repositories/6 in a new tab or existing tab, then press All repositories & it will go to the last page shown in that tab...

**Comment by pgleeson** [comment]
Maybe related... https://github.com/OpenSourceBrain/OSBv2/issues/483#issuecomment-1123904152

**Comment by filippomc** [comment]
Different issue here: https://github.com/OpenSourceBrain/OSBv2/blob/317fabc112b4400e27968d406fdbce91199f2bbf/applications/osb-portal/src/pages/RepositoryPage.tsx#L324

Can replace `history.goBack` with `history.push("/repositories")`
