### ISSUE TITLE
Connect user to JupyterHub

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#49]
When a workspace is open, a parameter `user` is sent on the query string.

At the moment, JupyterHub manages users its own way, creating a user for each session and keeping its own database of users. We want to use the user name coming from the parameter instead. Beware the same user will have a different session for each workspace.

Implementation:
Use the harness_jupyter library.

**Comment by zsinnema** [comment]
after reading the documentation of the keycloak (openid connect) for example here https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/authentication.html it seems that there is only one (1) session per user account.

**Comment by zsinnema** [comment]
also this is very interesting: https://jupyterhub.readthedocs.io/en/1.1.0/reference/config-user-env.html#named-servers

it should allow multiple single servers per user
