### ISSUE TITLE
Fix toggling light/dark theme in JupyterLab

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#491]
For anyone who prefers to use the lighter theme. Would just apply to JupyterLab frame.

![Screenshot from 2022-05-13 08-35-39](https://user-images.githubusercontent.com/1556687/168234734-a35d5717-6e47-4390-ae06-0ffd230befe8.png)

**Comment by filippomc** [comment]
Guess it's a file permission issue

**Comment by filippomc** [comment]
From the logs: `PermissionError: [Errno 13] Permission denied: '/home/jovyan/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/themes.jupyterlab-settings'`

**Comment by pgleeson** [comment]
Thanks for the tip. Fixed on v2dev now.
