### ISSUE TITLE
A new workspace should inherit all of the tags of its repository

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#494]
Discussed a number of times, but making an explicit issue. Any irrelevant tags can be removed in the initial create dialog, but should be there by default.

**Comment by filippomc** [comment]
@pgleeson duplicate? I think this is working now

**Comment by pgleeson** [comment]
I think not. If a repo has lots of tags and you create a new workspace from it, it doesn't get all those tags by default...

**Comment by filippomc** [comment]
Ah right, I was getting confused by the other functionality that inherits repository tags from remote.
Do you think tags should be inherited only when creating a brand new workspace from a repository or also while adding resources from a repository to a preexisting workspace?

**Comment by pgleeson** [comment]
> Ah right, I was getting confused by the other functionality that inherits repository tags from remote. Do you think tags should be inherited only when creating a brand new workspace from a repository or also while adding resources from a repository to a preexisting workspace?

I think it's fine to only add the tags on the creation of a new workspace from a repo.

**Comment by pgleeson** [comment]
@filippomc Did you suggest this was fixed already? Doesn't seem to work on dev
