### ISSUE TITLE
Scroll not working on user page when lots of workspaces or repositories

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#498]
e.g. https://www.v2.opensourcebrain.org/user/0103eaaf-6a34-4509-a025-14367a52aa2b

**Comment by sanjayankur31** [comment]
It's something styling related, but unfortunately my limited knowledge of CSS/MUI-styling isn't enough to fix it :(

**Comment by filippomc** [comment]
Need to add the `verticalFit` class here: https://github.com/OpenSourceBrain/OSBv2/blob/264498b3512acc608e57fd31dbd38a1bbd24121c/applications/osb-portal/src/pages/UserPage.tsx#L244

**Comment by sanjayankur31** [comment]
> Need to add the `verticalFit` class here:
> 
> https://github.com/OpenSourceBrain/OSBv2/blob/264498b3512acc608e57fd31dbd38a1bbd24121c/applications/osb-portal/src/pages/UserPage.tsx#L244

Tried this, doesn't seem to work for me here..

**Comment by sanjayankur31** [comment]
@filippomc would you take a look at this when you have a minute please? adding `verticalFit` didn't work for me, so now I'm not sure what else to try.

**Comment by filippomc** [comment]
Done! The trick is to specify the 100% height through the whole parent-child chain

**Comment by sanjayankur31** [comment]
Ah, right, and here we use `verticalFill`, not `verticalFit` too---I'll have to see what the difference between the two is. Thanks!

**Comment by pgleeson** [comment]
fixed
