### ISSUE TITLE
Options for Public and Featured should be visible/changable in Edit Workspace dialog

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#501]
Would be the logical place to be able to change these...
Slightly related to #499

**Comment by sanjayankur31** [comment]
I guess we could add checkboxes there or a drop down or something?

**Comment by pgleeson** [comment]
@filippomc @Aiga115 The PR related to this is merged into develop, but it doesn't seem to be there on live. Has it been done?

**Comment by pgleeson** [comment]
Sorry, I was looking at the repository dialog... This is live in the WS edit dialog
