### ISSUE TITLE
cell mechanisms don't show as circles

### ISSUE THREAD

**Issue by ddelpiano** [OpenSourceBrain/OSBv2#509]
**Describe the bug**
<img width="1027" alt="170507093-ca4cc8f3-dbd1-4951-8898-7ae66fb7189a" src="https://user-images.githubusercontent.com/37704177/170711881-c98d5b90-b4b4-489f-8f44-cd4d44406cb8.png">

same happens for import from python, the folder icons don't show up, and also the iplot traces

**To Reproduce**
1. open netpyne and follow the screenshot

**Comment by pgleeson** [comment]
Seems to be fine on live...
