### ISSUE TITLE
Complete essential data on workspaces

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#52]
Workspaces are being created with only a title and a markdown description.

Add the following fields to the data structure and add/edit form:
 - thumbnail: Image - insert with a dropdown zone. Not mandatory
 - types: WorkspaceType[] - represent the allowed applications that can open the workspace. Now we set with the application selected when creating the workspace
 - lastType: the last applociation saving in the workspace. By default, the application selected at creation
 - modified: Date - the last modified date. By default, same as created
 - created: creation date (automatically set)

All data will be stored in the WorkspaceManager database.

- [x] Design edit form on Figma
- [x] Implement Workspace manager data structure and necessary fields
- [x] Implement the rest api to upload/download the image
- [x] Implement new edit form accordingly to the design on Figma
- [ ] Update the workspace list in order to show the image, modified date and lastType

**Comment by zsinnema** [comment]
i've done the work for workspaces app and refactored osb-portal

added 5 new rest api's:
add a workspace type to a workspace, call this everytime a workspace is opened to update the workspace last type: (POST) workspace/<id>/type/add

delete a workspace type from a workspace: (GET) workspace/<id>/type/<type_id>/delete

add an image to the workspace gallery: (POST) workspace/<id>/image/add

delete an image from the workspace gallery: (GET) workspace/<id>/image/<image_id>/delete

set the thumbnail of a workspace: (POST) workspace/<id>/thumbnail/put


see swagger ui for more info
https://workspace.osb.local/api/ui/

**Comment by zsinnema** [comment]
@jrmartin I saw in the POST call to create a new workspace that you push the thumb as a string. For me that's ok but this is not the upload function for putting a thumb in a workspace.

I'm not sure if you already changed it. This is the RestAPI function you should use to upload a Thumbnail for a workspace:
```
workspacesControllerWorkspaceSetthumbnail
```

**Comment by filippomc** [comment]
Remove last edited label and add hour:minute
