### ISSUE TITLE
Not all branches are shown in dropdown in add repo dialog when many branches present

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#521]
e.g. try adding https://github.com/neuronsimulator/nrn, master not shown. Also not really in alphabetical order...

<img width="1582" alt="Screenshot 2022-06-22 at 11 11 57" src="https://user-images.githubusercontent.com/1556687/175004477-da5a5eac-7e09-471b-872d-6f9e2e2b5846.png">

**Comment by filippomc** [comment]
This is coming from the github api being paginated: https://api.github.com/repos/neuronsimulator/nrn/branches. 
Master is in the second page: https://api.github.com/repos/neuronsimulator/nrn/branches?page=2. Wonder whether we want to really show all the branches and tags or if it makes sense to filter to remove stale and merged branches

**Comment by pgleeson** [comment]
Ok, but we can't really second guess what the user wants to do. It is possible to increase the num returned but just to 100:
https://api.github.com/repos/neuronsimulator/nrn/branches?per_page=100

**Comment by pgleeson** [comment]
Fixed now
