### ISSUE TITLE
Link to keycloak user page in admin interface broken

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#529]
It includes "realms/osb2dev" in the url, which I presume is the issue.

**Comment by sanjayankur31** [comment]
I thought I'd taken care of that already:

https://github.com/OpenSourceBrain/OSBv2/blob/develop/applications/backoffice/src/pages/HomePage.tsx#L86

I wonder if this commit hasn't made it to live yet?

**Comment by filippomc** [comment]
Release/0.5.2 branch is on live: https://github.com/OpenSourceBrain/OSBv2/blob/release/0.5.2/applications/backoffice/src/pages/HomePage.tsx

**Comment by filippomc** [comment]
I suggest to change the implementation to use the value from https://v2dev.opensourcebrain.org/keycloak.json.

**Comment by sanjayankur31** [comment]
Happy to change the implementation, but what's the bug in the current implementation?

**Comment by sanjayankur31** [comment]
Ah, it's one of them silly JS things. indexOf returns -1, which does not mean `false`. So I also need to do `!== -1` in the second conditional. Fixing this now first, we can change the implementation later

**Comment by filippomc** [comment]
`includes` can be used in place of indexOf

**Comment by pgleeson** [comment]
Still broken. Would be much easier to admin users if this is fixed, as  can't order by date in userlist on keycloak

**Comment by sanjayankur31** [comment]
It's been fixed and the PR merged. Did this not make it to the deployment?

**Comment by sanjayankur31** [comment]
@filippomc : could you please check if this commit is part of whatever is currently deployed? (otherwise I haven't a clue why it's still broken)

**Comment by filippomc** [comment]
Yes this was lost in the release/0.5.2 branch. Merged back and deploying to dev

**Comment by sanjayankur31** [comment]
> Yes this was lost in the release/0.5.2 branch. Merged back and deploying to dev

Hrm---that's odd: where are we losing commits :thinking: ? I thought :

- we work on development where all new changes come in
- branch off from there for a release: where more commits/fixes come in
- merge back release branches to development and master to make sure extra commits there are included in future releases/development

So we shouldn't be losing commits anywhere. If there's somewhere in the workflow where there's a chance of us losing work, we need to tweak that. (We shouldn't realise this happening on live after a couple of new releases)

**Comment by filippomc** [comment]
missed to merge back 0.5.2 to dev. My bad

**Comment by sanjayankur31** [comment]
Ah, no worries. As long as our workflow doesn't have a loophole/bug somewhere, it's all good :)

**Comment by filippomc** [comment]
https://admin.v2.opensourcebrain.org/ still broken

**Comment by pgleeson** [comment]
Still broken on live. @filippomc should this have been fixed?

**Comment by filippomc** [comment]
will check that again and be sure it's fix for 0.5.5
