### ISSUE TITLE
Improve performance on workspace page loading

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#537]
Currently remains stuck with a blank page, with no spinner

**Comment by sanjayankur31** [comment]
![image](https://user-images.githubusercontent.com/102575/177571048-d2d6b3ba-61db-4c1d-908e-78cc98c57e41.png)


This seems to be the API call that's slow

**Comment by filippomc** [comment]
That's the one getting the workspace's data. Probably it's related to the user's data retrieval for permission check as the workspace retrieval is a simple query. Will do some profile/debug

**Comment by filippomc** [comment]
The slowness is related to a call to get the workflows which is not properly filtered. The logic is used to check whether there are still pending resources: https://github.com/OpenSourceBrain/OSBv2/blob/8b2d97d5c1f84c973066a82ab3503b187f104977/applications/workspaces/server/workspaces/service/model_service.py#L251
Issues:
- The listing is not filtered properly on cluodharness https://github.com/MetaCell/cloud-harness/issues/517 
- Looking for a big number of results, which is unneeded (the last ones are the relevant ones)
- Workflows are not getting cleaned up properly in some cases.

As a first action, cleaning up the workflows manually

**Comment by pgleeson** [comment]
Much quicker now
