### ISSUE TITLE
Frozen after loading from github zip

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#538]
https://youtu.be/bsA0KyKWZXY?t=2209

Sometimes seems that files don't get downloaded

**Comment by zsinnema** [comment]
@filippomc is it correct that in the video the download works as expected? Do you have any clues about when it looks like things get "frozen" or "not downloaded"?

**Comment by filippomc** [comment]
At minute 38 the chrome tab froze but I don't see that as related to the resource download in any way. Looks more  like chrome was out of memory to me. @pgleeson agree?

**Comment by pgleeson** [comment]
Yes, it doesn't seem like it was related to the download, and everything was there afterwards. Just an unexpected error which was resolved by reloading. Don;t think it's anything to spend too much time on now unless it happens again...

**Comment by pgleeson** [comment]
Closing unless we see soemthing like this again...
