### ISSUE TITLE
Remove branches from the imported resources path

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#540]
When importing from a repository ![image.png](https://images.zenhubusercontent.com/5c4f23c24557275e4b89d83b/82c58683-a03f-4d44-a31c-f1c45742973f)

**Comment by pgleeson** [comment]
Should probably be prioritised to fix on live... it would be quite confusing for users...

**Comment by pgleeson** [comment]
Fixed on live
