### ISSUE TITLE
Install plotly on jupyterlab

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#541]
```
pip install plotly
jupyter labextension install plotlywidget
```
Beware plotly and the extension must be the same version, otherwise the plot will show as blank (also other issues may make the plot show as blank)

**Comment by pgleeson** [comment]
Taking care of this in a Dockerfile update...

**Comment by zsinnema** [comment]
@filippomc I think we can mark this one as reviewsince @pgleeson already added it

**Comment by filippomc** [comment]
was this tested? I'm not sure this is enough to get plotly working, I got blank plots when I first tried

**Comment by pgleeson** [comment]
Yep. Try with the featured Neuron course workspace. Plots weren't working before, but are now...
<img width="1160" alt="Screenshot 2022-09-02 at 12 49 38" src="https://user-images.githubusercontent.com/1556687/188135318-955ba6cc-8583-488b-9d9c-8e97be632ce8.png">

**Comment by pgleeson** [comment]
On live...
