### ISSUE TITLE
Update to Arbor: new version

### ISSUE THREAD

**Issue by brenthuisman** [OpenSourceBrain/OSBv2#542]
Looking at the [docker image](https://github.com/OpenSourceBrain/OSBv2/blob/master/applications/jupyterlab/Dockerfile), I think no update is actually required, but I wonder what the rebuild frequency is of your image?

We just released Arbor v0.7.

**Comment by filippomc** [comment]
Hi @brenthuisman the image is usually updated upon each release, which is usually flexible and depending on specific needs, so we are open to do more releases as needed. Can see https://github.com/OpenSourceBrain/OSBv2/releases to have an idea of usual timelines.

**Comment by zsinnema** [comment]
@filippomc what do you want me to do? Is the problem that the docker step is "cached" and therefore not updating the library? thanks

**Comment by pgleeson** [comment]
@zsinnema This will be done automatically when the latest Dockerfile is deployed, we just pip install the latest Arbor

**Comment by zsinnema** [comment]
@pgleeson are you sure about this? Docker caches on build steps... in this case Docker can assume that it can use the cache

**Comment by pgleeson** [comment]
I guess that's why @filippomc  has lines like this in the other Dockerfiles: 
https://github.com/OpenSourceBrain/OSBv2/blob/056527c0548693478d955b44dd6c5a29b7aac28c/applications/netpyne/Dockerfile#L5.
Can be added to the dockerfile for jupyterlab too, though surely there's an option to specify not to use the caches and attempt a full rebuild before deploying..?

**Comment by zsinnema** [comment]
@pgleeson I suggest to add this to the Dockerfile. This will invalidade the cache when the head on master branch is changed
```
ADD https://api.github.com/repos/arbor-sim/arbor/git/refs/heads/master arbor-version.json
```

**Comment by filippomc** [comment]
@zsinnema that would work but would be specific for arbor

**Comment by pgleeson** [comment]
Agreed. I think in general it's reasonable to default to not using any caches on a full deployment. There's no reason to think what's left from the build last time is still relevant.

**Comment by filippomc** [comment]
@pgleeson caching is useful as the jupyterlab build takes about 30 minutes with the current version and builds are made quite often for the dev deployment. We are looking at ways to also speed up the build time (`chown -R` alone takes 10 minutes, should be avoidable by installing packages as jovyan in the first place)

**Comment by pgleeson** [comment]
Specific point of this issue (getting latest Arbor on live v2) is done, so closing. Caching build is a wider issue...
