### ISSUE TITLE
Cloud cluster restructuring

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#545]
The goal is to separate dev and production applications and separate user pods nodes from applications nodes.

- [x] Create new cluster osb-dev
- [x] Add a node pool with preemptible nodes (or spot vms) on osb-dev, 2 e2-medium nodes (2cpus, 2GB) with autoscale enabled. 
- [x] Move v2dev and beta.opensourcebrain.org pipelines to the osb-dev cluster. Update the codefresh pipelines as well
- [x] Configure the production cluster to separate user (jupyterhub) pods from service pods: create a node pool only for jupyterhub pods. All the service pods go on a node pool half the size of the current one (so from one e2-standard-8 to 2 e2-standard-4

**Comment by zsinnema** [comment]
@filippomc new osb-dev cluster is created, I restored (incl. the all data) the osb2dev and osb-staging namespaces. It seems that it's up&running. Can you check if everything is okay? 
Tomorrow I will do the osb production task

**Comment by zsinnema** [comment]
@filippomc osb-cluster task done. see 
![image](https://user-images.githubusercontent.com/124044/181728877-fbf1f2ca-e11f-4cca-9e03-2e6e4a94014c.png)

the one jupyter node is because someone started a jupyter notebook

**Comment by zsinnema** [comment]
I've enabled autoscaling on the service pool because there is just enough cpu allocatable to fulfill the requested cpu
