### ISSUE TITLE
Creating workspace from DANDI repo with all files fails

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#546]
e.g. https://v2.opensourcebrain.org/repositories/44

Creating workspace with just some selected files is working. Seem to recall this was an issue in the past too...

**Comment by sanjayankur31** [comment]
Hrm, yeh, I get "there was an error creating workspace" on both live and dev. Here's the error in the workspace/import API call:

```
XHRPOST https://v2dev.opensourcebrain.org/proxy/workspaces/api/workspace/137/import
[HTTP/2 500 Internal Server Error 112ms]

	
description	"'NoneType' object has no attribute 'group'"
type	"AttributeError"
trace	
"Traceback (most recent call last):\n File \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n rv = self.dispatch_request()\n 
File \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 1936, in dispatch_request\n return self.view_functions[rule.endpoint](**req.view_args)\n 
File \"/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py\", line 48, in wrapper\n response = function(request)\n File \"/usr/local/lib/python3.7/site-p…ers/etl_helpers.py\", line 22, in copy_origins\n path=origin.get(\"path\"),\n 
File \"/usr/src/app/workspaces/service/osbrepository/__init__.py\", line 62, in create_copy_task\n return repository_adapter.create_copy_task(workspace_id=workspace_id, name=name, path=path)\n 
File \"/usr/src/app/workspaces/service/osbrepository/adapters/dandiadapter.py\", line 129, in create_copy_task\n folder = re.search(\".*folder=(.*)$\", path).group(1)\nAttributeError: 'NoneType' object has no attribute 'group'\n"
```

**Comment by zsinnema** [comment]
@sanjayankur31 I can't reproduce this. I've tried on my local dev env, v2 live

can you give it another try and let me know? or if you know how to reproduce then please post it here. thanks!

**Comment by filippomc** [comment]
Still an issue -- try https://www.v2.opensourcebrain.org/repositories/44

**Comment by zsinnema** [comment]
steps to reproduce:
1. open the repo
2. do NOT select any file
3. click create a new workspace of this repo

results in a 500 error

**Comment by filippomc** [comment]
Change the message

**Comment by zsinnema** [comment]
@filippomc what message would you like to have?

**Comment by filippomc** [comment]
@pgleeson will write the message here

**Comment by pgleeson** [comment]
Change to: 

Note: due to the large size of files in most DANDI repositories, the default behaviour of adding all files to a new workspace when no files/folders are selected below is disabled. 
Please select specific files/folders to add to a workspace, bearing in mind the total size of the files.
