### ISSUE TITLE
Fix the default application to open a new workspace in

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#549]
Currently a not previously opened ws will show "Open with NWB Explorer" on the button on the ws page. Best to default to the one used when clicking on "open" last time

**Comment by filippomc** [comment]
Actually it does not default to NWB Explore, but it is connected to the last resource opened, which is not really effective being the resources not really clear atm. If no resource was used/loaded, Jupyterlab is the default.
Not sure if the last opened is a good solution though now that I think about it, as I see a pattern where the same workspace is being opened with netpyne and jupyterlab in sequence -- in that case jupyterlab would be the default. Thoughts @pgleeson ?

**Comment by pgleeson** [comment]
> If no resource was used/loaded, Jupyterlab is the default.

But this doesn't seem to be the case... however it actually decides what the "default" application should be, NWBE is what appears in the blue dropdown as selected in a new workspace...

This particular issue is really only related to what appears first in the blue button, not the underlying system of resources/applications

**Comment by filippomc** [comment]
I remember this default behaviour to go to nwb explorer but that was fixed. Created this as netpyne and did nothing then: https://v2dev.opensourcebrain.org/workspace/259

**Comment by filippomc** [comment]
The issue is when creating from a repository nwb explorer is the default until the first import ends

**Comment by filippomc** [comment]
@Aiga115 to replicate: create a new workspace from a repository then immediately go to the workspace and it will suggest to open with nwb explorer, regardless nwb files are selected. It settles back after the pending resource import tasks are finished. The default should be Jupyterlab until then instead

**Comment by filippomc** [comment]
@pgleeson do you think it would make sense to disallow opening a workspace until the first import has finished to avoid confision?

**Comment by pgleeson** [comment]
I think that could be a long time for some repos. I think the simplest solution is to make sure the drop down defaults to jupyterlab in most cases, as opposed to the NWBE.
