### ISSUE TITLE
Investigate cost on osb cluster

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#564]
- [x] enable billing access https://console.cloud.google.com/billing/linkedaccount?project=true-hook-230313
- [x] backup costs
- [x] number of clusters -- investigate how we can go back to one cluster
- [x] volumes (storage PD capacity)

**Comment by filippomc** [comment]
Consider contact google support

**Comment by zsinnema** [comment]
to move namespaces from one cluster to other (new) clusters we use the Google GKE backup option.
so also for moving the osbv2dev to the dev cluster.
first you switch on the gke backup switch of both cluster, then create a backup and restore parts in the (new) destination cluster. afterwards you switch off the gke backup switches in the cluster
however the backup data remains (against a cost) until you remove it
I've just removed the gke backups and restores

![image.png](https://images.zenhubusercontent.com/5e2079d495a332382cd766a5/19fd14b5-4e7a-45fb-8de8-453d30c38919)

**Comment by zsinnema** [comment]
@filippomc to move back to one cluster is just (because both run on GKE) a case of creating a backup and restore it in the other cluster. Then remove the cluster and remove the backup & restore

**Comment by filippomc** [comment]
cleaned up a number of workspaces on v2dev to lower down space cost

**Comment by filippomc** [comment]
Storage cost is about 15% of the total at the moment. Might remove old workspaces to reduce the costs and also keep the habit of deleting workspaces on v2dev will help keeping costs lower. 
Can also rethink a bit volume provisioning with a more flexible network storage which could be more easily tweaked to use only the space that is actually needed to contain files. That would be also beneficial as would allow the manytomany mounting to be implemented so removing the need of pod affinities and potential deadlocks. Removing pod affinities would also make the google autoscaler work properly, potentially having 0 nodes up by default when unused
