### ISSUE TITLE
Deep link into JupyterLab to open a specific notebook (or image/readme)

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#568]
Related to https://github.com/OpenSourceBrain/OSBv2/issues/302 (requires similar interaction with JupyterLab core to call function to open a specific file)

Idea is we can construct a URL which will open a workspace (probably public) in JupyterLab and open a specific notebook file known to be present, e.g.
https://www.v2.opensourcebrain.org/workspace/open/233/jupyter?file=NEURON%20Course%202022/main/notebooks/current_clamp_experiments.ipynb

Would require logging in of course before seeing the file. Could be extended to allow opening of any file with its default viewer

**Comment by filippomc** [comment]
Yes it would be nice to follow up this idea for any resource for any application for coherence

**Comment by pgleeson** [comment]
Works on live, but few tweaks required, will open new issues
