### ISSUE TITLE
Delete resource from workspace

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [OpenSourceBrain/OSBv2#573]
**To Reproduce**
1. Open a workspace
2. Click on the trash icon next to a resource in the resource list

**Expected behavior**
The resource should be removed from the workspace

**Actual behavior**
 When pressing the trash icon on a resource it deletes the resource but opens it with an application as well instead of just deleting it.

**Screenshots**

https://user-images.githubusercontent.com/99416933/188693091-7a7c1666-d9ba-4c93-8c9a-0c2338b98762.mov

**Comment by filippomc** [comment]
fixed

**Comment by SimaoBolota-MetaCell** [comment]
@filippomc fixed
