### ISSUE TITLE
Loading NWB file from inside a workspace broken

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#578]
I've not really been able to load an NWB file (by clicking on the resource on the left) when inside a workspace. Either it hangs or just part of the interface loads (what's in the background below)

<img width="1444" alt="Screenshot 2022-09-12 at 08 23 46" src="https://user-images.githubusercontent.com/1556687/189586697-a6823b96-f18d-4ce1-97fe-d7316fa3a838.png">

**Comment by pgleeson** [comment]
@filippomc This issue and #300 are 2 which are preventing NWBE working well on OSB currently, and should be prioritised

**Comment by filippomc** [comment]
Yes this is an important regression. @SimaoBolota-MetaCell can you please add this to the manual tests?

**Comment by SimaoBolota-MetaCell** [comment]
@filippomc of course, adding it

**Comment by filippomc** [comment]
Could replicate on dev: https://v2dev.opensourcebrain.org/workspace/open/150
