### ISSUE TITLE
Update NetPyNE branch in jupyterlab docker to use 'osbv2-dev'

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/OSBv2#580]
It needs to be:

https://github.com/OpenSourceBrain/OSBv2/blob/develop/applications/netpyne/Dockerfile#L26

Currently it's "osbv2" in requirements.txt:

https://github.com/OpenSourceBrain/OSBv2/blob/develop/applications/jupyterlab/requirements.txt#L9

**Comment by filippomc** [comment]
since we are releasing wouldn't it be better to update the osbv2 branch? I think we should do the same on netpyne-ui

**Comment by filippomc** [comment]
@sanjayankur31 thoughts?

**Comment by sanjayankur31** [comment]
Sorry, missed the notification---I don't think we care about what particular branch it is as long as it's the latest netpyne/netpyne ui branche that we need on v2.

**Comment by filippomc** [comment]
not sure what action to take still. Should we release with osbv2-dev branch or are you updating the osbv2 branch to have the latest?

**Comment by sanjayankur31** [comment]
We'll need to wait till Padraig returns from leave for this one.

**Comment by filippomc** [comment]
@pgleeson thoughts?

**Comment by pgleeson** [comment]
@filippomc The https://github.com/suny-downstate-medical-center/netpyne/tree/osbv2 branch now has all the latest changes from the netpyne core dev branch and should be used in both the jupyterlab and netpyne-ui dockerfiles. The version will show up as `1.0.3.1_osbv2`
