### ISSUE TITLE
Limit number of simultaneous pods per each user

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#583]

**Comment by zsinnema** [comment]
@filippomc there is a setting about the max number of jupyter pod you can have running per user. 

see https://jupyterhub.readthedocs.io/en/stable/reference/config-user-env.html#named-servers

In CH 1 I set this to max 10 (https://github.com/MetaCell/cloud-harness/blame/4d4546242471c58621387a453b658741ca90e357/applications/jupyterhub/deploy/values.yaml#L15) 

In CH 2 I can see it's not set

**Comment by filippomc** [comment]
Yes mentioned on #585 . Closing this for now. I agree we could set a default also on ch

**Comment by filippomc** [comment]
covered within #248
