### ISSUE TITLE
Use pip install for MDF

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#587]
Just 'pip install modeci_mdf' here: https://github.com/OpenSourceBrain/OSBv2/blob/e74a9a943c86e705d18417380ce7ad8821dd88a7/applications/jupyterlab/requirements.txt#L38-L45

**Comment by filippomc** [comment]
Not sure I follow this issue: would you like to install modeci_mdf without a specific version specified?

**Comment by pgleeson** [comment]
Mainly that MDF is stable enough to manage its own dependencies now, and the rest can probably be removed (after testing)
