### ISSUE TITLE
Should markdown text in workspace readme be centrally aligned?

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#588]
e.g. https://www.v2.opensourcebrain.org/workspace/406. Probably not...

Or is it only when there's a thumbnail..?

<img width="1420" alt="Screenshot 2022-09-16 at 16 48 54" src="https://user-images.githubusercontent.com/1556687/190667192-1186759d-7efa-41ee-a532-17928ea27ded.png">

**Comment by filippomc** [comment]
Agree it should not
