### ISSUE TITLE
Choosing an application from a workspace is not working

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [OpenSourceBrain/OSBv2#596]
**Describe the bug**
Choosing an application from a workspace is not working

**To Reproduce**
1. Open a workspace
2. Click on the downwards arrow (to choose an application to open the workspace with)

**Expected behavior**
You should be able to get the list of available applications and select them

**Screenshots**

https://user-images.githubusercontent.com/99416933/194121212-a71949bf-94a2-4679-a7fb-d3deee3bf25e.mov

**Comment by pgleeson** [comment]
Believe this is no longer an issue...
