### ISSUE TITLE
Strange behaviour in drop down filter for Types of repos

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#598]
To reproduce, click on Filter, click on Experimental (-> blue tick there), click on Modelling  (-> blue tick there), click on  Modelling again (Experimental becomes unticked)

<img width="492" alt="Screenshot 2022-10-06 at 09 40 09" src="https://user-images.githubusercontent.com/1556687/194264948-1f675bef-b8c6-4d38-8b1d-7665e4f9197f.png">

**Comment by filippomc** [comment]
Yes this is bugged, there is also another similar bug open https://github.com/OpenSourceBrain/OSBv2/issues/574

**Comment by pgleeson** [comment]
Looks like it's fixed
