### ISSUE TITLE
Editing E-mail in Account Page

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [OpenSourceBrain/OSBv2#602]
**Describe the bug**
Editing E-mail in Account Page is allowed and does not save after refreshing

**To Reproduce**
1. Go to 'My Account'
2. Click on 'Edit Profile'
3. In the e-mail field, wirte some e-mail
4. Click on 'Save changes'
5. Refresh page
6. Click on 'Edit Profile'
7. e-mail is no longer specified

**Expected behavior**
From talking with @filippomc the e-mail field should either be hidden or unable to edit

**Screenshots**

https://user-images.githubusercontent.com/99416933/195305184-ccf3f305-0bcc-41b7-a078-785453ca40ef.mov

**Comment by filippomc** [comment]
It's better to show the email, at least in the left side
