### ISSUE TITLE
Design group page and view workflows

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#604]
Baseline: https://www.opensourcebrain.org/groups/7
Meta data: https://accounts.v2.opensourcebrain.org/auth/admin/master/console/#/realms/osb2/groups/71f15e46-399a-4cdc-9fb7-25c60fa3a46e/attributes

Also need a page with the groups list

**Comment by filippomc** [comment]
@pgleeson wonder whether it would be relevant to see:
- group's users workspaces and repositories
- group's quotas (maybe only if logged in as a group member)

**Comment by pgleeson** [comment]
Yes, maybe the first one, so all users in the Silver Lab should be listed, and all public workspaces (or repos) for those users should be open to all
I suspect the groups used for managing users will need to be protected (e.g Users level 1, Users level 2), and not relevant for most users, and so should be flagged as special in some way. In the first instance a user only needs to see their access/quota levels, on their own account page, which will be the outcome of the standard method to generate max_num_workspaces etc. from all the group/user attributes they have.
