### ISSUE TITLE
Add resource from remote url to Workspace

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#61]
The first way we provide to add a file to a workspace is through a remote url. The used is prompted for the url on a modal window as per mockup:

![image.png](https://images.zenhubusercontent.com/5c4f23c24557275e4b89d83b/f36461dc-2dec-4e34-8ff5-5a4cef0abe8e)

Being the only available way to add a resource we *do not* implement here the selector buttons (by url, repository, etc).

The process is performed in a cloud ETL task using Cloudharness' workflow functionality.

- [ ] Implement modal and the call on the portal application
- [x] Implement the main ETL task. Create inside the workspaces application: applications/workspaces/tasks/load-url and a docker file on it. Use https://github.com/MetaCell/cloud-harness/blob/master/applications/workflows/tasks/extract-download/Dockerfile as a blueprint
- [x] Implement backend to load a resource from remote url on Workspaces application - `POST /api/workspaces/resource?url=[URL]&name=[NAME]`. This will create a resource entry on the database in pending status and will launch the workspaces-load-url task inside an asynchronous workflow operation.
- [ ] Close the loop with the ETL pipeline. The loading process adds a *workspace-resource-ready* to the events queue after the first step is done. Use https://github.com/MetaCell/cloud-harness/tree/master/applications/workflows/tasks/send-result-event as a blueprint
- [ ] The Workspaces application listens to the  *workspace-resource-ready* event and updates the status of the resource from *pending* to *ready*

The following sequence diagram describes the whole process (includes the portal resource list handling, not implemented here in this task): 
![OSB-NetPyNE Architecture - OSB2 data loading (2).png](https://images.zenhubusercontent.com/5c4f23c24557275e4b89d83b/91f61964-4561-422d-b065-f875d70b6559)

**Comment by zsinnema** [comment]
herewith some comments:
1. why have a status on the resource? what/who benefits from that?
2. what if the download workflow "crashes"
3. there is no description how to store the file in the workspace pvc also it's no clear "who" stores the pvc
4. what if the file size exceeds the available space on the a. the mounted volume of the download task, b. workspace pvc

ideas:
1. pass the workspace pvc to the download task so it will download directly into the workspace pvc
2. if the download is finished correctly do "something" on the file to enable/show it in the workspace, I would like to solve the issue of the status keeps pending in case of a "crash"

**Comment by filippomc** [comment]
Follow up of clarification chat:
1. The status can be used to show the user the pending loading. We definitely need a way to give feedback to the user about the process. Given the weak point in case of failure we are open to equivalent alternatives. My favourite at the moment is to leave the status there but at the same time have a queryable reference from workflows to resources. This will allow to query the status of the workflow in case of failure to have more information (and eventually abandon/retry).
2. Investigate out-of-the-box solutions from Argo to handle exception cases, another good alternative would be to have a final step that runs whatever happened before. An alternative can be to use the workflow itself to identify pending tasks rather than the database to store the resource (so the resource will actually be saved only at the and of the process)
3. The ETL task mounts the volume and stores the file there directly
4. Need to make a choice on the user's side: do we want the volume to resize based on the required space (not doable in the current scenario in which we add file with the application running with mounted volume) or do we want the upload process to fail and have another workflow to handle workspace volume resizing? For now, we just make the process fail

**Comment by filippomc** [comment]
@tarelli comes into mind we probably need to add the naming of the resource to the interface. We could have some convention from the url but that may not be enough in some practical cases. Sometimes the download link is something like /download?id=2 so this approach

**Comment by tarelli** [comment]
We can add another optional field with the same style then we can get Paul to review it
