### ISSUE TITLE
NWBE doesn't find random nwb resource to load if mix of nwb & ipynb resources

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#611]
e.g create a new ws from https://www.v2.opensourcebrain.org/repositories/38 & open in NWBE

Perhaps it's choosing an ipynb as the default to open and related to issue #610?

**Comment by filippomc** [comment]
The current behaviour is to try open the last opened resource if no resource was clicked, ant that leads to #610 when the resource is not the same type of the current application - can easily fix this.
Can also tackle this together with the above one
