### ISSUE TITLE
Implement workspace volume provisioning with NFS

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#614]

**Comment by filippomc** [comment]
@pgleeson after we move to the NFS solution old workspaces with old volumes will continue to work. If we want to free up the space, need to delete the workspaces. Could also migrate to the new solution in the production cluster if we want to, but would need dedicated time

**Comment by pgleeson** [comment]
I suspect there are a lot of current workspaces on live that are just for testing purposes, and I can go through mine to get rid of them. In that case it would certainly be good to permanently delete the volumes too. The new NFS solution can have a softer aproach, maybe moving to a backup folder, but for now, if someone presses delete workspace (especially with the warning on the homepage), it's reasonalble if the data is permanently gone.

So maybe implement hard volume delete on live, and we can clean up before moving to the NFS solution?

**Comment by filippomc** [comment]
The nfs migration is going to be a soft one, old workspaces will keep being where they are and with the current volumes. I think it's  a good idea to delete old test workspaces either way to free some space reserved by the current volume provisioner

**Comment by pgleeson** [comment]
> The nfs migration is going to be a soft one, old workspaces will keep being where they are and with the current volumes.

Great, that's what I understood would happen.

> I think it's a good idea to delete old test workspaces either way to free some space reserved by the current volume provisioner

Sure. Does there need to be any updates though before the current workspaces can be safely deleted, i.e. so the volume/space is fully freed?

**Comment by filippomc** [comment]
> Sure. Does there need to be any updates though before the current workspaces can be safely deleted, i.e. so the volume/space is fully freed?

No, old workspaces can be deleted at any time

**Comment by pgleeson** [comment]
Working nicely...
