### ISSUE TITLE
Implement application restyling

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#628]
Figma mockups: https://www.figma.com/file/E2W6Gh7yjaLaY3lo9PCm40/OSB2%2FNetPyNE%2FNWBE?node-id=0%3A1&t=uujgFsikafOsORlT-0

**Comment by Salam-Dalloul** [comment]
- [ ] view profile page >> new design is ready
- [ ] Edit my profile dialog
- [ ] Add repo to existing workspace dialog 
- [ ] repo dialog along with adding the uploader >> @Salam-Dalloul 
- [ ] workspace details page >> @Aiga115 
- [ ] Workspace open page sidebar (NetPyne, Jupyter) >> @Aiga115 
- [ ] repo details page
