### ISSUE TITLE
Fix add resource from repository

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#629]
- Filter doesn't work
- After selecting a repo keeps spinning
- Add a manual test for it

See also #625

**Comment by pgleeson** [comment]
Broken still. Basically  you can list them but nothing you click on selects the repo...
![Screenshot 2023-03-29 at 14 22 22](https://user-images.githubusercontent.com/1556687/228551885-9ebbc501-e437-4251-8cc1-2306542cd1f7.png)

**Comment by filippomc** [comment]
Need to be sure that the button is always visible

**Comment by filippomc** [comment]
can click on the title too now
