### ISSUE TITLE
Listing of DANDI repo contents not working...

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#635]
e.g. https://www.v2.opensourcebrain.org/repositories/49

Have they changed their API again..?

**Comment by pgleeson** [comment]
Also on dev. Note button for create workspace also disabled for DANDI...

**Comment by filippomc** [comment]
Looks like the api to get the files is broken atm, e.g. https://api.dandiarchive.org/api/dandisets/000147/versions/draft/assets/paths/.

Nothing we can do about that

**Comment by sanjayankur31** [comment]
It's still an issue though. At the moment, the user just sees a broken OSB. We need to then somehow inform the user that DANDI is currently broken and that they should check back later. An error of some sort needs to be thrown there.

**Comment by filippomc** [comment]
@sanjayankur31 yes agree

**Comment by filippomc** [comment]
to do: open issue on dandi

**Comment by filippomc** [comment]
Created issue on Dandi: https://github.com/dandi/dandi-archive/issues/1396

**Comment by filippomc** [comment]
@pgleeson solved on current dev

**Comment by pgleeson** [comment]
Fixed
