### ISSUE TITLE
Move netpyne osb for not logged-in users

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#637]
- read only workspace opening
- time limit (e.g. 15 minutes)
- old links must be working

**Comment by filippomc** [comment]
in scope doing the estimates for now

**Comment by filippomc** [comment]
need to clarify the requirements: is it correct to say that nwbexplorer.opensourcebrain.org should go to osb instead?

**Comment by pgleeson** [comment]
@filippomc netpyne is moved, but is it the plan to also retire the standalone nwbexplorer?

**Comment by filippomc** [comment]
Might be a good idea. Need to dedicate some attention to make sure that the links used by Dandi will work properly

**Comment by pgleeson** [comment]
Ok, maybe better to not change anything for now, until we have an updated nwbe on osb...

**Comment by pgleeson** [comment]
Closing as this is live
