### ISSUE TITLE
'See more' / 'See less' has a weird behaviour

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [OpenSourceBrain/OSBv2#656]
**Describe the bug**
Adding a new repository works
But on the 'My Repositories' tab, the 'See more' / 'See less' for the repo description has a weird behaviour as seen in the screen recording

https://user-images.githubusercontent.com/99416933/210260541-b7d4d12b-f244-4cf1-ae0f-2981a10e233f.mov

**To Reproduce**
1. Go to 'My Repositories'
2. Click on 'See More'
3.Click on 'See Less'

**Expected behavior**
The repository description should expand and collapse

https://v2dev.opensourcebrain.org/

**Comment by filippomc** [comment]
@SimaoBolota-MetaCell I'm not able to replicate, can you please try to add one more repository and see if that fixes the issue for you?

**Comment by SimaoBolota-MetaCell** [comment]
@filippomc It seems to be fixed now


https://user-images.githubusercontent.com/99416933/218787873-fbebbc85-e6bf-41a0-9445-d2d85fe23f0c.mov
