### ISSUE TITLE
Improve maximum number of concurrent workspaces detection

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#673]
Also closed workspaces are adding to the count and now need to delete manually.

**Comment by zsinnema** [comment]
@filippomc with "closed workspaces" you mean "not running" but still in the list of workspaces (on url `hub/home`), right?

**Comment by pgleeson** [comment]
I think that was the issue yes. Regarding user experience, some workspaces which had been open in a tab, but which had been closed days ago were still counted towards their 3 workspaces which they could have "open" at one time.
