### ISSUE TITLE
Direct links for sign in and register?

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#674]
Is there a url which will lead directly to the screens for logging in or registering, e.g. 
https://www.v2.opensourcebrain.org/login
https://www.v2.opensourcebrain.org/register

Needed for the new homepage and https://docs.opensourcebrain.org/OSBv2/Guided_tour.html

**Comment by filippomc** [comment]
ok, adding those links to go to register and login

**Comment by pgleeson** [comment]
Thanks @filippomc. Might be useful too to have a page like https://www.v2.opensourcebrain.org/myaccount also, in addition  to the current long one with the full userid

**Comment by filippomc** [comment]
It would be easier to just replace the long userid with the named one to avoid confusion, agree @pgleeson?

**Comment by filippomc** [comment]
yes usernames are unique

**Comment by filippomc** [comment]
moving to a separate issue
