### ISSUE TITLE
netpyne.opensourcebrain.org broken?

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#687]
I'm getting a jupyterhub login screen

Also at gui.netpyne.org...

**Comment by filippomc** [comment]
It's a consequence of the helm charts update. The login is free, can enter any username or password

**Comment by pgleeson** [comment]
Would really be good if it just went straight to the netpyne-ui view. Would probably put of a few potential users...
Would you agree @salvadord?

**Comment by filippomc** [comment]
To be clear, this is about netpyne.opensourcebrain.org and there's no sign up actually, just sign in with any random credentials.
In any case I don't recommend to give any compute power without signing up though as it's too easy for an attacker to get free resources to do crypto mining or other nasty things out of control and taking resources to other users. As a way to reduce the impact of this, we are giving limited resources and planning to turn off users pods in that deployment after a short amount of time.
You can all verify that there are no equivalent compute systems around not requiring sign up around.

It is not possible to implement access to workspaces without signing up to users on v2.opensourcebrain. What we could do to reduce the impact to the user is implementing convenient third party sign up like google, github or ORCID.

**Comment by pgleeson** [comment]
Getting a strange issue with https://netpyne.v2.opensourcebrain.org in Firefox... Log in as normal to v2 in one private window, non admin user, open 3 workspaces, then in another new private window, try https://netpyne.v2.opensourcebrain.org, and it says that there are too many ws open, listing the ones inthe other window...

**Comment by pgleeson** [comment]
I'll redirect https://netpyne.opensourcebrain.org/ to ppoint at https://netpyne.v2.opensourcebrain.org/

**Comment by pgleeson** [comment]
Closing this issue as it's working , but the other issue #734 is still there.
