### ISSUE TITLE
Creating a repository - Type 'Development' does not exist

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [OpenSourceBrain/OSBv2#693]
**Describe the bug**
Development appears as a type to filter the repositories
However it is not present when creating a new repository
so you can never have a development repository at the moment

**To Reproduce**
1. Go to the homepage
2. Click on repositories
3. Open the filter options and see the 3 types
4. Go back to the homepage and create a repository. On the type field, there is no 'Development'

**Expected behavior**
The types should match

**Screenshots**

![image](https://user-images.githubusercontent.com/99416933/222694418-1367aadb-47f0-4160-90cd-573d9a33e13f.png)

![image](https://user-images.githubusercontent.com/99416933/222694471-2c1edaff-ed9c-4054-ba27-a2a5e4ec725a.png)

**Comment by filippomc** [comment]
@pgleeson I don't remember the "development" type to have been discussed, do you? I wonder whether we should just remove it from the filter
