### ISSUE TITLE
Slider on NWB console graphs resets right away

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [OpenSourceBrain/OSBv2#697]
**Describe the bug**
The slider on the graphs works but resets right away

**To Reproduce**
1. Go to the homepage
2. Click on a workspace
3. Open the workspace with NWB Explorer
4. Open an experiment
5. In the python console run 'show()'
6. Click on a graph tab and move the slider

**Expected behavior**
The slider shoud fix its position and not reset

**Screenshots**

https://user-images.githubusercontent.com/99416933/222699713-d461b1f6-608e-492e-8d54-ad397d87daa0.mov

**Comment by filippomc** [comment]
This is most probably a nwbwidget issue, may try to update and see if this is fixed

**Comment by SimaoBolota-MetaCell** [comment]
Not fixed yet @filippomc

**Comment by filippomc** [comment]
definitely a nwb widget issue, closing.
