### ISSUE TITLE
JupyterLab - can't open python kernel through the Notebook section

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [OpenSourceBrain/OSBv2#708]
**Describe the bug**
When opening a workspace using Jupyter Lab, the user can't open python kernel through the Notebook section but from the console section the user is allowed.

**To Reproduce**
1. Go to the homepage
2. Click on a workspace
3. Open it with Jupyter Lab
4. Once it is loaded, click on Python 3 (ipykernel) in the Notebook section
5. See the error

**Screenshots**
![image](https://user-images.githubusercontent.com/99416933/225979843-4ed7ff6c-4e67-47fa-983c-fe69e65ebe61.png)

**Comment by filippomc** [comment]
cannot reproduce

**Comment by filippomc** [comment]
This happens with non-admin users

**Comment by SimaoBolota-MetaCell** [comment]
Fixed! @filippomc
