### ISSUE TITLE
No spinning wheel on new workspace searching for resources

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#718]
When a new workspace is created, and there are known resourses in the ws, the left column on the workspace page is initially blank, as opposed to showing a spinnign circle or other indication that it is searching for resource files.

**Comment by pgleeson** [comment]
If not an easy fix, can be moved to 0.7.2

**Comment by filippomc** [comment]
Not working if creating a workspace from a repository

**Comment by pgleeson** [comment]
Fixed
