### ISSUE TITLE
Confirmation dialog needs correct link

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#720]
When verifying email, and clicking on the link in the email, you get this screen:
<img width="427" alt="Screenshot 2023-03-29 at 14 45 29" src="https://user-images.githubusercontent.com/1556687/228558662-3e68faf7-27ed-4b2d-90cd-e484b5916040.png">

But click here to proceed takes you to https://accounts.v2.opensourcebrain.org/auth/realms/...

**Comment by filippomc** [comment]
fixed
