### ISSUE TITLE
Add github and orcid login

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#727]
- [x] add github @filippomc 
- [x] add ORCID @filippomc 
- [x] implement styling @Salam-Dalloul

**Comment by filippomc** [comment]
fix labels

![Image](https://github.com/OpenSourceBrain/OSBv2/assets/46561561/d414fa6e-9e1a-40ab-b530-5e966b3caa5a)

**Comment by filippomc** [comment]
Add github and orcid also in the registration form -- follow the same structure and style

**Comment by Salam-Dalloul** [comment]
updated register page figma design


![Image](https://github.com/OpenSourceBrain/OSBv2/assets/32265731/01207f78-5b0f-41fa-921a-8d6ddab12b31)
