### ISSUE TITLE
Copying tags from a repository to the create new workspace dialog seems to have stopped working

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#733]

**Comment by pgleeson** [comment]
No, I meant an OSB repo which has tags set by the user etc. Then when you create a workspace from that the tags are not copied. Think it worked before...

**Comment by filippomc** [comment]
right, that should have worked

**Comment by filippomc** [comment]
couldn't replicate

**Comment by filippomc** [comment]
works from my tests

**Comment by filippomc** [comment]
Doesn't work starting from a repository, like https://v2dev.opensourcebrain.org/repositories/143

**Comment by pgleeson** [comment]
Fixed on live
