### ISSUE TITLE
Workspace resource view enhancements

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#737]
- [ ] Notebooks list is collapsed by default (e.g. https://v2.opensourcebrain.org/workspace/749) even though there are notebooks in there:
<img width="314" alt="Screenshot 2023-05-18 at 10 59 55" src="https://github.com/OpenSourceBrain/OSBv2/assets/1556687/7d4eda49-a223-45f3-b2ef-449ddc754595">

- [ ] Filenames are truncated even though there is plently of space (column for bin could be made narrower)
<img width="389" alt="Screenshot 2023-05-18 at 11 02 41" src="https://github.com/OpenSourceBrain/OSBv2/assets/1556687/66aeb85d-5690-48a2-b775-b4c37891ef38">

**Comment by pgleeson** [comment]
Ok, so maybe put the total number of them beside the type, e.g. Experimental Data (4), Notebooks (3)

**Comment by filippomc** [comment]
good idea

**Comment by SimaoBolota-MetaCell** [comment]
The following problems are now fixed:

Workspace resources list is collapsed only if it's not the current active list

![Image](https://github.com/OpenSourceBrain/OSBv2/assets/99416933/a4e44bc5-1e6b-4894-a4d2-f8c0b79803cc)




Full filenames are now visualized and not truncated

![Image](https://github.com/OpenSourceBrain/OSBv2/assets/99416933/b5c9d9cd-af25-4d4a-8076-6d293b504975)

Thanks @Aiga115 
cc @filippomc
