### ISSUE TITLE
Warn when non-admin user tries to open private workspace

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#739]
All of these should give warning that workspace is private when a different non-admin user tries to open them (they just get a blank page):

https://v2.opensourcebrain.org/workspace/751
https://v2.opensourcebrain.org/workspace/open/751/nwbexplorer
https://v2.opensourcebrain.org/workspace/open/752/jupyter?resource=LoadNetPyNEData.ipynb

**Comment by pgleeson** [comment]
Also, even when it's my workspace, and my session has timed out, if I go to/refresh any of these that I own I don't get a warning to log in, I just see a blank page...

**Comment by pgleeson** [comment]
Related to #793

**Comment by SimaoBolota-MetaCell** [comment]
As a user with no access to the 751 workspace in dev, I am encountering the error but nothing is displayed to the user @D-GopalKrishna @filippomc 

![Image](https://github.com/OpenSourceBrain/OSBv2/assets/99416933/9463d2e2-887a-4007-bc26-043601e7c4a9)

**Comment by D-GopalKrishna** [comment]
Hi @SimaoBolota-MetaCell , the PR for this issue is not yet merged! thanks!

**Comment by D-GopalKrishna** [comment]
Hi @SimaoBolota-MetaCell , the PR for this issue is not yet merged! 
here - https://github.com/OpenSourceBrain/OSBv2/pull/862

thanks!
