### ISSUE TITLE
Match name of resource with name of the file

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#74]

**Comment by pgleeson** [comment]
Not sure this is the best option for some use cases. Say someone wants to add Ferguson1.nwb, Ferguson2.nwb, Ferguson3.nwb, etc. Now they'll get 3 new folders, each with one NWB file (if i understand correctly), possibly in ./Ferguson1.nwb/Ferguson1.nwb, etc. They may add the first one (naming the resource Ferguson) and then try to add more in that folder, but that will require calling the resource Ferguson again (is that allowed?)

It may be better for now (until zip suppport is added) to allow the user to add the URL, and the dialog automatically assigns the resource name as the last part of the URL (e.g. Ferguson1.nwb). This can be overridden if required but the default behaviour is the filename is the same as that on the remote resource, and the file goes in at top level. 

There could be an optional entry in the dialog to specify a folder for the imported resource (with the default as . ), which would enable the functionality above by default, and also allow organisation of multiple files into folders (existing folders could be offereed as options in the dialog). This would require some support for folders in the drawer though.

**Comment by zsinnema** [comment]
@pgleeson zip files are supported by the download task

for me the main question is:
  is a resource 1-to-1 equal to a file

this is still unclear to me

and in case a resource is a zip file containing many files and folders, do we then create "sub" resources for each file?

and what about repository resources, how to support this
======
an approach could be to list all files in the resource folder under the resource as sub items
this could be a solution for multi file resources like zip files and repositories

**Comment by pgleeson** [comment]
I think if it's anyway unclear to you/us, then the term resource will be completely unclear to users...

I think the one concept that will be clear is "you can copy some files locally to your workspace and access them again". This is understandable if it's a single file or a zip originally, so maybe it's best not to use the term "resource" much in the UI, just give them the chance to add files (or dirs/files from zips) and list all of these in the drawer.

I realise that some resources will be accessed not as a locally copied version, but listed in the remote resource/repository, but these could be shown as "read-only" files in the drawer...
