### ISSUE TITLE
Move NWB explorer for non-logged-in users

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#758]
nwbexplorer.opensourcebrain.org uses the osb2 deployment.  Must ensure that links from dandi continue work

**Comment by filippomc** [comment]
Works: https://nwbexplorer.v2dev.opensourcebrain.org/?nwbfile=https://api.dandiarchive.org/api/assets/7a3d889c-b513-40d6-b3e9-74ccb24e4412/download

**Comment by filippomc** [comment]
Redirect done, have to setup the ingress configuration

**Comment by filippomc** [comment]
@pgleeson nwbexplorer.opensourcebrain.org redirect works now

**Comment by pgleeson** [comment]
Done!
