### ISSUE TITLE
Move new homepage to www.opensourcebrain.org

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#760]
It would be great if the first page people see when they go to opensourcebrain.org is the [new homepage](https://www.v2.opensourcebrain.org/), which can be made almost completly v2 focussed now. It will still be fine if the main v2 pages still have v2 in the url, but the following would be ideal

- https://www.opensourcebrain.org -> new homepage
- https://opensourcebrain.org -> new homepage
- https://v1.opensourcebrain.org -> old v1 homepage
- https://www.opensourcebrain.org/ANYTHING -> existing v1 urls, e.g. https://www.opensourcebrain.org/projects/
- https://opensourcebrain.org/ANYTHING -> existing v1 urls, e.g. https://opensourcebrain.org/projects/
- https://v2.opensourcebrain.org/ANYTHING -> keep as is...

**Comment by filippomc** [comment]
Move redmine v1 first is required. Then we can setup the redirects

**Comment by filippomc** [comment]
- [ ] check the ingress to map to v1
- [ ] reconfigure redmine internal links/configuration
- [ ] move the dns
