### ISSUE TITLE
Creating new workspace from repository errors, hangs page: only from user profile page (works file from osbv2 landing page)

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/OSBv2#762]
**Describe the bug**
When creating a new workspace from a repository, if I don't select any tags for the workspace in the workspace editor, the webapp errors and hangs. 

On refreshing my profile page later, though, it seems like the workspace was created, but the files I selected were not imported

**To Reproduce**
1. Go to user profile page
2. Click on 'create new workspace"
3. Click on "from repository"
4. Choose a repo
5. Click "open details"
6. Choose a file
7. Click continue
8. In workspace editor, remove any tags
9. Click "create new workspace"
10. See error

**Expected behavior**
Workspace should be created

**Screenshots**
![image](https://github.com/OpenSourceBrain/OSBv2/assets/102575/db46b3d5-12ba-4ac7-845e-9859f1f807cb)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 114

**Smartphone (please complete the following information):**

**Additional context**
Video here: https://www.dropbox.com/scl/fi/u5ph75h7w9powff8pjoqo/202306261438-osb-create-new-workspace-error.webm?dl=0&rlkey=5vyv8y1096c5mipfthwpf6gsi

Also other errors in the devtools bar, but not quite looked into them yet.

**Comment by sanjayankur31** [comment]
Hrm, no, I'm always getting the error, even if there's a tag present. See:  https://www.dropbox.com/scl/fi/uhtnq1bueh4ve7yjlo09n/202306261448-osb-create-ws-errors.webm?dl=0&rlkey=aan9yuk7dr7wtbc5x3wtoxnf4

**Comment by pgleeson** [comment]
@sanjayankur31 Could you check whether this is still an error?

**Comment by filippomc** [comment]
@D-GopalKrishna the dialog now shows up by opening a repository https://v2dev.opensourcebrain.org/repositories/143

**Comment by pgleeson** [comment]
Fixed on live
