### ISSUE TITLE
Add resources to workspace dialog - buttons not shown properly

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#769]
<img width="1656" alt="Screenshot 2023-07-10 at 12 23 51" src="https://github.com/OpenSourceBrain/OSBv2/assets/1556687/d364028c-2109-45a8-bf8d-3865c03afbc5">

**Comment by D-GopalKrishna** [comment]
@pgleeson, is this screenshot of the desktop view? 
For me it looks fine in the desktop view. 


cc @filippomc

**Comment by pgleeson** [comment]
Still seeing this on the live site... 
Firefox:
![Screenshot 2023-11-08 at 11 06 18](https://github.com/OpenSourceBrain/OSBv2/assets/1556687/a05eb29b-ba74-494e-bc64-b7e8d8c1d88e)
Chrome:
<img width="1590" alt="Screenshot 2023-11-08 at 11 05 34" src="https://github.com/OpenSourceBrain/OSBv2/assets/1556687/8cd54c2c-e254-41d3-9fce-91547ff42665">

depends on your screen size too I think...

**Comment by pgleeson** [comment]
Done
