### ISSUE TITLE
Workspace name in side bar misaligned in Firefox

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/OSBv2#771]
![image](https://github.com/OpenSourceBrain/OSBv2/assets/102575/1b707637-a880-4c1e-836f-df907c0f5dd6)

It looks misaligned. Should be centered in the side bar? ^

**Comment by pgleeson** [comment]
Seeing that too, but only on Firefox..

**Comment by pgleeson** [comment]
Fixed
