### ISSUE TITLE
Logo on login page needs updating

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/OSBv2#773]
Also noticed that the logo on the login page is not the new one:

![image](https://github.com/OpenSourceBrain/OSBv2/assets/102575/e845ebc3-b36f-41df-a84e-0dc08d4cb663)

**Comment by filippomc** [comment]
The above screenshot doesn't match the latest login screen but yes, it is still ooutdated
![image](https://github.com/OpenSourceBrain/OSBv2/assets/46561561/381fb2ff-dbb9-4100-ab9f-8528c80d48ce)
