### ISSUE TITLE
Add "Manage running workspaces" button on user account page

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#776]
i.e. link to https://notebooks.v2.opensourcebrain.org/hub/home below the list of Maximum quotas on the user's info page (just visible for that user)
![Screenshot 2023-07-11 at 13 49 15](https://github.com/OpenSourceBrain/OSBv2/assets/1556687/41210f20-5876-4ccd-ac88-09a52005c791)

**Comment by D-GopalKrishna** [comment]
Since this is not in the designs, Which of the following seem more appropriate here? 

![image](https://github.com/OpenSourceBrain/OSBv2/assets/59233227/197585ed-8d63-4b6b-b776-b5c56059158c)

cc @filippomc

**Comment by filippomc** [comment]
The outlined version, just like the Edit my profile above it

**Comment by pgleeson** [comment]
@D-GopalKrishna Probably the one on the left, to match the existing Edit my Profile...

**Comment by filippomc** [comment]
like this: ![image](https://github.com/OpenSourceBrain/OSBv2/assets/46561561/a25d8d8e-25ee-4035-baa5-2d24323a1833)

**Comment by filippomc** [comment]
@pgleeson the above was proposed by Sya, the graphic designer, The good is it takes less space and it makes clear it goes outside the current scope

**Comment by pgleeson** [comment]
Looks good!

**Comment by pgleeson** [comment]
Pressing this on v2dev results in https://v2dev.opensourcebrain.org/user/notebooks.v2dev.opensourcebrain.org/hub/home.
Please double check @D-GopalKrishna @filippomc
