### ISSUE TITLE
URL with NWB file to load not working for NWBE

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#778]
Tried these links, https://docs.opensourcebrain.org/OSBv2/NWBE.html#osbv2-applications-nwbe, Github one slow to load, other 2 broken.

**Comment by filippomc** [comment]
This is not related to OSBv2 and actually the nwbexplorer.opensourcebrain.org has not been updated recently. Indeed it needs optimizations for many use cases, including the https://github.com/openworm/WormsenseLab_ASH/raw/main/test_data/07-06-25-1.nwb, which is not big on size but has lot of time series in it
Move to the nwbeplorer repo @pgleeson ?

**Comment by filippomc** [comment]
Works on latest OSBv2: https://nwbexplorer.v2dev.opensourcebrain.org/?nwbfile=https://github.com/openworm/WormsenseLab_ASH/raw/main/test_data/07-06-25-1.nwb. Next step, redirect NWB explorer to the v2 deployment as done with netpyne
