### ISSUE TITLE
Some redirects to v1 not working 

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#790]
Not sure if it's due to recent updates but these both should be redirected to v1:

http://opensourcebrain.org/projects/blue-brain-project-showcase
http://www.opensourcebrain.org/projects/blue-brain-project-showcase

but only the second one does. Any idea @filippomc @etowett?

**Comment by etowett** [comment]
I am not really sure about the redirection because the recent update didn't update the domain `opensourcebrain.org`. As far as I am concerned, the `www.opensourcebrain.org` is serving github pages that are static.

@filippomc can provide more context here.

**Comment by filippomc** [comment]
It's matched here https://github.com/OpenSourceBrain/OSB_homepage/blob/main/404.html, maybe the 404 is not hit without www?

**Comment by pgleeson** [comment]
Bigger issue is http://opensourcebrain.org simply doesn't work.

Shouldn't this get redirected to www (potentially fixing the other issues)?

**Comment by pgleeson** [comment]
@filippomc Fairly urgent now, as we may have used that link with no www in the application...

**Comment by pgleeson** [comment]
Seems to be fixed now. Thanks for originally reporting this @wvangeit.
