### ISSUE TITLE
Standalone NWBExplorer not working 

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#791]
Spawn failed on: http://nwbexplorer.opensourcebrain.org

**Comment by filippomc** [comment]
This appeared to be trickier than expected as the jupyterhub version used is apparently incompatible with the current version of kubernetes. Prioritizing #758 to use the OSB deployment as base for nwbexplorer.opensourcebrain.org

**Comment by filippomc** [comment]
My suggestion is to redirect http://nwbexplorer.opensourcebrain.org/ to https://nwbexplorer.v2.opensourcebrain.org. Let's be sure that the redirect keeps the parameter `nwbfile`

**Comment by pgleeson** [comment]
Closing as a version is deployed here.
