### ISSUE TITLE
Warning/404 for non existent pages

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#793]
Rather than showing a (partially) blank page e.g. 
https://v2.opensourcebrain.org/jfhjgj -> should be 404
https://v2.opensourcebrain.org/workspace -> should be 404
https://v2.opensourcebrain.org/workspace/1abcd -> should be: You do not have access to a workspace with that ID
https://v2.opensourcebrain.org/user/pglee -> should be no such user

**Comment by D-GopalKrishna** [comment]
What is better?
- a 404 page or
- a snackbar with

**Comment by sanjayankur31** [comment]
Let's do a page, that seems cleaner?

**Comment by filippomc** [comment]
Before the restyling, it used to be there a blank error page with a modal in the middle about the error (401, 404, or whathever else) and a button to go the homepage. I'd go for that as a catch all for any kind of issue to avoid the design of a new page. @sanjayankur31 @pgleeson what do you think?

**Comment by sanjayankur31** [comment]
Yeh, I think that sounds good.

**Comment by filippomc** [comment]
Two things to configure:
- error boundary
- non existing pages route

**Comment by SimaoBolota-MetaCell** [comment]
I am still getting blank pages for the following @D-GopalKrishna @filippomc 

- https://v2dev.opensourcebrain.org/ahshfh where I was expecting a 404 to be displayed 
![image](https://github.com/OpenSourceBrain/OSBv2/assets/99416933/310b7f80-7675-4763-96d9-51f7b74fc686)

- https://v2dev.opensourcebrain.org/workspace where I was expecting a 404 to be displayed 
![image](https://github.com/OpenSourceBrain/OSBv2/assets/99416933/fad3a23f-ce45-439e-9161-8cf97377054e)

- https://v2dev.opensourcebrain.org/workspace/akjdhasj got a 404 but it is not displayed to the user 
![image](https://github.com/OpenSourceBrain/OSBv2/assets/99416933/74b9dbf4-f371-40e7-b03d-24f7cf8edbe5)

- https://v2dev.opensourcebrain.org/workspace/224 got a 401 for non authorized but it is not displayed to the user 
![image](https://github.com/OpenSourceBrain/OSBv2/assets/99416933/5d0c35bf-8619-4f6f-9cf4-a9345f641927)

- https://v2dev.opensourcebrain.org/user/pglee got a 404 not found but it is not displayed to the user 
![image](https://github.com/OpenSourceBrain/OSBv2/assets/99416933/ef88d7a5-4b81-4c00-ac67-dcc15563fcf2)
