### ISSUE TITLE
Update nwb explorer links

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#795]
Now http://nwbexplorer.opensourcebrain.org/hub/nwbfile, should be http://nwbexplorer.opensourcebrain.org/?nwbfile=...

**Comment by pgleeson** [comment]
DANDI Archive have been told in the past to use a link of the form (which used to but no longer works): 
http://nwbexplorer.opensourcebrain.org/nwbfile=https://dandiarchive.s3.amazonaws.com/blobs/724/0a5/7240a588-db87-4526-8223-cb43b4bea092

Can this not be still supported without requiring them (and others) to update their urls?

**Comment by filippomc** [comment]
The above link is not syntactically correct, not sure where it's been taken from. Should be ?nwbfile=

**Comment by pgleeson** [comment]
Hopefully this line is all that will need to change to fix it on their side...
https://github.com/dandi/dandi-archive/blob/b38aa93ed9162c05ba95edfac7d0b9cba40a5ff0/web/src/views/FileBrowserView/FileBrowser.vue#L319

**Comment by pgleeson** [comment]
@filippomc This (with slash as you suggest):
http://nwbexplorer.opensourcebrain.org/?nwbfile=https://github.com/openworm/WormsenseLab_ASH/raw/main/test_data/07-06-25-1.nwb
goes to the hub page at https://nwbexplorer.v2.opensourcebrain.org/hub/home

This (no slash)
http://nwbexplorer.opensourcebrain.org?nwbfile=https://github.com/openworm/WormsenseLab_ASH/raw/main/test_data/07-06-25-1.nwb
fails initially, by going to nwbe homepage, then if url is put into same tab again, works sometimes...

**Comment by filippomc** [comment]
Fixes are on dev: https://nwbexplorer.v2dev.opensourcebrain.org/nwbfile=https://github.com/openworm/WormsenseLab_ASH/raw/main/test_data/07-06-25-1.nwb 

https://nwbexplorer.v2dev.opensourcebrain.org?nwbfile=https://github.com/openworm/WormsenseLab_ASH/raw/main/test_data/07-06-25-1.nwb

**Comment by pgleeson** [comment]
Thanks. FYI issues with plotting any trace (clicking on eye):

<img width="1714" alt="Screenshot 2023-11-10 at 09 35 52" src="https://github.com/OpenSourceBrain/OSBv2/assets/1556687/1337297f-ba90-4224-a422-6ec582dd8bad">

**Comment by filippomc** [comment]
fixed

**Comment by pgleeson** [comment]
@filippomc Do you mean it's fixed on dev or live? For live, now both the urls above (with and without slash) now go to the hub. On dev, the link works, but the plots don't show...

**Comment by filippomc** [comment]
Right, the fixed version of NWB explorer wasn't deployed on v2dev yet. Nothing has been changed on live.

**Comment by pgleeson** [comment]
Closing as the preferred form is working. Need to update DANDI links...

**Comment by pgleeson** [comment]
See https://github.com/dandi/dandi-archive/pull/1755 for DANDI url update status
