### ISSUE TITLE
Logging out in the main osb portal should ideally log a user out from all services

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#797]
I've logged out in the main osb portal, but other services/urls such as:
https://notebooks.v2.opensourcebrain.org/hub/home
https://netpyne.v2.opensourcebrain.org
https://admin.v2.opensourcebrain.org/
continue as if I'm logged in as that user.

**Comment by filippomc** [comment]
Increased the expiration token duration so this does not affect the user.
