### ISSUE TITLE
Loading NWB Explorer with figshare file not working

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [OpenSourceBrain/OSBv2#809]
**Describe the bug**
I was loading nwbexplorer with the different files listed here https://docs.opensourcebrain.org/OSBv2/NWBE.html#osbv2-applications-nwbe
 - from github
 - from dandi
 - from figshare
and I could for all of them except for figshare to which I'm getting an error and infinite load

**To Reproduce**
1. Load https://nwbexplorer.v2dev.opensourcebrain.org/?nwbfile=https://github.com/openworm/WormsenseLab_ASH/raw/main/test_data/07-06-25-1.nwb  replacing the contents of `?nwbfile=` with the urls from https://docs.opensourcebrain.org/OSBv2/NWBE.html#osbv2-applications-nwbe

**Expected behavior**
The NWB Explorer should load with the data

**Screenshots**
![image](https://github.com/OpenSourceBrain/OSBv2/assets/99416933/e74ab019-e43a-475e-afb2-920f96f8acae)

**Desktop (please complete the following information):**
 - dev
 - Chrome

**Comment by filippomc** [comment]
I'm having troubles downloading that file locally https://figshare.com/ndownloader/files/22248861

**Comment by SimaoBolota-MetaCell** [comment]
I was able to download it @filippomc 

![image](https://github.com/OpenSourceBrain/OSBv2/assets/99416933/48a205dc-0b3d-49db-b5f2-6020e933f0d4)

(can't upload it here as it doesn't allow to upload .nwb files)

**Comment by filippomc** [comment]
The correct link is without ?: http://nwbexplorer.opensourcebrain.org/nwbfile=https://github.com/openworm/WormsenseLab_ASH/raw/main/test_data/07-06-25-1.nwb. Docs will be updated
