### ISSUE TITLE
Error when deleting the Workspace Resources

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [OpenSourceBrain/OSBv2#812]
**Describe the bug**
The user cannot delete a workspace resource as an error is thrown in the console

**To Reproduce**
1. Go to 'the application
2. Launch a workspace with any application
3.Click on '+' in the sidebar to add a workspace and add it
4. Once it is displayed in the workspace resources, click on the trash icon next to the added resource

**Screenshots**

https://github.com/OpenSourceBrain/OSBv2/assets/99416933/f76c939b-1c2c-4781-b9f6-68969bea85b5

**Comment by filippomc** [comment]
In the video, the error in the console is relevant

**Comment by SimaoBolota-MetaCell** [comment]
Still happening, might be relevant for this release

https://github.com/OpenSourceBrain/OSBv2/assets/99416933/95b2b2f4-9683-4462-9450-068ebdd15cb2

@filippomc
