### ISSUE TITLE
Dialog Create a new NWB workspace from Blue button should give option Open workspace

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#816]
i.e. a workspace is created with example nwb data from the bottom left blue button, but the dialog just closes and the option to open directly is not given.

**Comment by D-GopalKrishna** [comment]
@pgleeson - I believe the expectation is also for any of the following options. That is, if a new workspace is created through any medium, we should be shown a dialog to go to new workspace.


<img width="485" alt="image" src="https://github.com/OpenSourceBrain/OSBv2/assets/59233227/22ed33b0-b52f-4236-9eb2-8b183e07cd8b">

**Comment by pgleeson** [comment]
@D-GopalKrishna Yes, that's the assumption.

**Comment by pgleeson** [comment]
Works on live
