### ISSUE TITLE
NWBE standalone fails on 1st (and 2nd) load, works after that

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#820]
Direct URLs with the current preferred format (http://nwbexplorer.opensourcebrain.org/?nwbfile=...), e.g. as used on https://github.com/OpenSourceBrain/DANDIArchiveShowcase/blob/main/validation_folder/README.md#000399 should open the nwb file directly in NWBE.

What I'm finding is on a new session, the first load of the link goes to the notebook control centre/hub (where you go for "Manage running workspaces"), the second load goes to the NWE homepage, and the third load goes to the correct page. Every subsequent link after that goes to the correct page (hence making it difficult to debug/notice the issue during testing, but new users may well give up before the 3rd try).

When a user is logged in on OSB, the step of the control hub is skipped, but the NWBE homepage shows first time around.

@etowett Is this something you could look into? If you can replicate this and see if there is any subsequent error message on the cluster it would be great.

**Comment by SimaoBolota-MetaCell** [comment]
Tested successfully

NWB Explorer works standalone
See below:

following the URL - https://nwbexplorer.v2dev.opensourcebrain.org/nwbfile=https://github.com/openworm/WormsenseLab_ASH/raw/main/test_data/07-06-25-1.nwb - leads to NWB Explorer loaded with the correct data 

![Image](https://github.com/OpenSourceBrain/OSBv2/assets/99416933/7aca3b45-2686-4c00-b582-5b687bce30f3)


![Image](https://github.com/OpenSourceBrain/OSBv2/assets/99416933/1eea6fcb-bd37-4a3b-be01-ed17b926aa33)



While following a different URL - https://nwbexplorer.v2dev.opensourcebrain.org/nwbfile=https://github.com/openworm/WormsenseLab_ASH/raw/main/test_data/09-07-15-2.nwb - leads to NWB explorer loaded with different data 

![Image](https://github.com/OpenSourceBrain/OSBv2/assets/99416933/addde40d-d362-4a72-85db-8046418267fd)



![Image](https://github.com/OpenSourceBrain/OSBv2/assets/99416933/ae578066-ca7e-4061-a06c-f46da985b80f)

**Comment by pgleeson** [comment]
This is not working on live.
http://nwbexplorer.opensourcebrain.org/nwbfile=https://api.dandiarchive.org/api/assets/14df4c07-159e-471c-afae-7af889d01539/download/ 
goes to the nwbe homepage on first load for a logged out user (also for logged in user). In fact it never loads after 2nd, 3rd try. That's the currently preferred form of the url, isn't it @filippomc?

**Comment by filippomc** [comment]
I works with https://nwbexplorer.v2.opensourcebrain.org/nwbfile=https://api.dandiarchive.org/api/assets/14df4c07-159e-471c-afae-7af889d01539/download/, so there's something about the redirect. Will investigate that

**Comment by filippomc** [comment]
fixed. Also works with http://nwbexplorer.opensourcebrain.org?nwbfile=https://api.dandiarchive.org/api/assets/14df4c07-159e-471c-afae-7af889d01539/download/

**Comment by pgleeson** [comment]
Great! Links on DANDI Archive site as well as https://github.com/OpenSourceBrain/DANDIArchiveShowcase/blob/main/validation_folder/README.md working nicely now...

I did notice though that if you load 2 different nwb files in separate tabs as an anonymous user with nwbe, they seem to both use the same kernel, so the nwbfile info in the second gets put into the first, i.e. the undeerlying model in both is the same.. Feature or bug..?

**Comment by filippomc** [comment]
yes the second one will overload the first. Can make so the two go on separate pods, but that would require to dedicate resources for another pod. Is this something we want or do we say we support only one file at a time?
