### ISSUE TITLE
Searches in tag filter box in Repositories are case sensitive - no reason they should be

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#823]
e.g. search for SBML & sbml

**Comment by pgleeson** [comment]
The tab filter search seems to be case insensitive in the workspaces view...

**Comment by pgleeson** [comment]
Moving to urgent, as this seems an easy fix, and should be done and tested beside the other search updates.

**Comment by filippomc** [comment]
fixed on https://v2dev.opensourcebrain.org/

**Comment by pgleeson** [comment]
Looks good on v2 dev!
