### ISSUE TITLE
Tag filter search for workspaces doesn't work on Features workspaces view

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#824]
This is the search for the tag DANDI
- clearly not all are dandi repos
- The tab says there are 15, 10 are shown here, there are 5 on the next page for some reason
<img width="1475" alt="Screenshot 2023-11-23 at 11 59 34" src="https://github.com/OpenSourceBrain/OSBv2/assets/1556687/df712bb1-3b9b-40ee-9cba-8a3f19a09166">

**Comment by filippomc** [comment]
15 is the total of results, which are paginated by 10. Pagination upon filtering should match the default pagination, which is 24 @D-GopalKrishna

**Comment by SimaoBolota-MetaCell** [comment]
Using the tag to filter the workpace lists works for

- `Featured workspaces`
- `Public workspaces`

https://github.com/OpenSourceBrain/OSBv2/assets/99416933/f680117a-85e3-4f48-a242-ddf891c93b69


but not working and returning an error for `My Workspaces`

https://github.com/OpenSourceBrain/OSBv2/assets/99416933/093dd67d-a9ec-441d-bcca-7a5e5a08949e

@filippomc @D-GopalKrishna

**Comment by D-GopalKrishna** [comment]
thanks @SimaoBolota-MetaCell! Made changes and pushed.

cc @filippomc

**Comment by SimaoBolota-MetaCell** [comment]
Fixed! Thank you @D-GopalKrishna 


https://github.com/OpenSourceBrain/OSBv2/assets/99416933/d8bf0265-3163-4d0b-82f8-ccd3d4beb6eb


cc @filippomc

**Comment by pgleeson** [comment]
Fixed on live
