### ISSUE TITLE
Searches in workspace search bar return entries whose tabs match, but not repositories search 

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#828]
e.g. search for "ecog" - this will return LFPy in workspaces search, but the repository LFPy is missing from repository seach results.

**Comment by pgleeson** [comment]
1. Yes, searching for ecog in workspaces (on v2 live) returns this as the only featured workspace found: https://www.v2.opensourcebrain.org/workspace/188, and the only reason it matches is the tag EGoC. Ideally the search should cover title & tags, all independent of capitalisation. The issue is that searching in resources doesn't search in the tags
2. See https://v2.opensourcebrain.org/workspace/188. Note: this repo should show up in a search on repos for ecog, as it has that tag: https://v2.opensourcebrain.org/repositories/32

**Comment by D-GopalKrishna** [comment]
thanks for the explaination @pgleeson ! 

I noticed the same issue as you mentioned and will be fixing the tags issue with this one.

**Comment by pgleeson** [comment]
Current workspace Search on live is worse than it was... searching for a term adds it to the tabs filter, and matches on that. However if you remove it from the tabs filter is returns either no entries or all entries. 
Basic search on workspaces is broken, please prioritise...

**Comment by filippomc** [comment]
@pgleeson please check the latest on https://v2dev.opensourcebrain.org/. Works as you described from my tests

**Comment by pgleeson** [comment]
Looks good! It would be great to get a hot fix with these changes on live asap.
