### ISSUE TITLE
Username with accent preventing workspaces to load

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#829]
**Describe the bug**

The bug is caused by the fact that the username is used as a label and the regex is not removing all characters correctly.
After some attempts, jupyterhub restarts.

` HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"ws-benjamínrodriguez-1046-netpyne\" is invalid: [metadata.name: Invalid value: \"ws-benjamínrodriguez-1046-netpyne\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: \"benjamínrodriguez\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]","reason":"Invalid","details":{"name":"ws-benjamínrodriguez-1046-netpyne","kind":"Pod","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"ws-benjamínrodriguez-1046-netpyne\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","field":"metadata.name"},{"reason":"FieldValueInvalid","message":"Invalid value: \"benjamínrodriguez\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')","field":"metadata.labels"}]},"code":422}`

**Comment by filippomc** [comment]
It's simpler to handle the removal of the non-alphanum characters when building kubernetes labels, as actually keycloak allows UTF-8 usernames and has no restriction embedded.

**Comment by SimaoBolota-MetaCell** [comment]
Tested successfully.

Created the following new user with username `anaíscão` and the application allows the user to load a workspace correctly 

![Image](https://github.com/OpenSourceBrain/OSBv2/assets/99416933/03009f63-7881-43ea-8d3f-72a4a6ba43e5)


![Image](https://github.com/OpenSourceBrain/OSBv2/assets/99416933/c8ceff41-eb71-4db0-b223-6744a0b87f46)

@filippomc
