### ISSUE TITLE
Usernames are not matched exactly

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#831]
**Describe the bug**

From a user: "My account name reads Arthur Powanwe, my name is theo herbst, could this possibly be rectified please?

**Comment by filippomc** [comment]
Diagnosis: accounts api is not using the param exact from https://www.keycloak.org/docs-api/23.0.0/rest-api/index.html#_users, so usernames are not matched strictly

**Comment by sanjayankur31** [comment]
Can we apply a hotfix for this ASAP? We got ~70 new users in November, so chances of this bug cropping up for various users is high, especially if they have small usernames with common sub-strings.

**Comment by filippomc** [comment]
Yes it's in the urgent queue, ETA this week

**Comment by SimaoBolota-MetaCell** [comment]
How can I check this fix? @filippomc 
I created a new user and got the info I registered with

**Comment by pgleeson** [comment]
This seems to be working on v2dev. https://v2dev.opensourcebrain.org/user/pgleeson is my page, but https://v2dev.opensourcebrain.org/user/pglee used to return that page too (incorrectly, as there might be another user with that name), but is now just blank (not ideal but better).

**Comment by pgleeson** [comment]
Fixed on live
