### ISSUE TITLE
General requirements for search boxes

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#835]
As there are a few related open issues related to search in repos and workspaces, I'm just outling here the general principles that the search boxes should aim for. 

The golden rule is that since the search box is the only things that's visible to the user (the tab filter needs to be clicked to show it), typing something in here should search over the maximum number of fields to find something for the user (independent of capitalisation). 

So for workspaces, all of the text shown (title, summary, tabs, even username if possible) should be searched over:

<img width="732" alt="Screenshot 2023-12-05 at 15 21 20" src="https://github.com/OpenSourceBrain/OSBv2/assets/1556687/f7a9c36e-3247-40fb-b56d-1d4440da668f">

Similarly for repositories.

The tab filter should be considered an advanced setting for refining search results, by specifying an exact string for the required tab, though this can be case insensitive. Typing something in the search box shouldn't add anything in the tab filter. 

Generally, behaviour of the search box/tab filter should be the same for both repository and workspace pages, either thumbnail or list views.

**Comment by pgleeson** [comment]
@filippomc @D-GopalKrishna @SimaoBolota-MetaCell @sanjayankur31  please let me know if any of the above is not in line with how you believe(d) the searching/filtering should work, and we can discuss.

**Comment by filippomc** [comment]
@pgleeson the current implementation of the search is much simpler (LIKE match on title and tag match) and is as what you suggest would be ideal but requires a more sophisticated implementation of indexes as the more we include, the less the search is filtering out, so it's necessary to implement a relevance based sorting, so rely on a full-text-search engine. This is especially true the moment that we include the summary. Also including the username could lead to complications performance wise as usernames sit in another database. How much do we want to push

**Comment by pgleeson** [comment]
Ok, lets just concentrate on getting the search working consistently on the title and tags for now. Another current issue is the search box adding entries to the tab filter, which in turn stay there when you delete the text in the search box, leading to confusing behaviour:

<img width="1434" alt="Screenshot 2023-12-06 at 12 10 41" src="https://github.com/OpenSourceBrain/OSBv2/assets/1556687/04eef1fc-8f0d-427e-851b-b7b8f2c1909d">

**Comment by D-GopalKrishna** [comment]
Yes I will address that here - https://github.com/OpenSourceBrain/OSBv2/issues/828#issuecomment-1842848965

thanks! @pgleeson

**Comment by pgleeson** [comment]
@filippomc It seems the repositories search does search over the summary text too, here 'recognize' in the text is matched for the search term 'ecog'...
<img width="1460" alt="Screenshot 2023-12-07 at 13 35 27" src="https://github.com/OpenSourceBrain/OSBv2/assets/1556687/b7cdb633-474c-4755-b727-66b0a2710669">

**Comment by filippomc** [comment]
Yes true, although not sure it makes sense now with a lot repositories without full-text search and relevance sorting

**Comment by pgleeson** [comment]
Can't see any reason to remove it unless it impacts performance. All the more reason to be able to refine the search with AND linked tab searches.

**Comment by filippomc** [comment]
It does not impact performances, it's more about having a relevant sorting as matches in titles and tags should bump higher than matches in long text. This becomes more evident with lots of content and using generic words

**Comment by pgleeson** [comment]
I am intensely relaxed about someone searching for a term and getting lots of relevant, correct matches...

**Comment by pgleeson** [comment]
Closing as this is generally how it's implemented now.
