### ISSUE TITLE
Loading a file in NWBE via a click on NWB resource while Jupyterlab open should warn about navigating away from page

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#839]
As is the case when reloading jupyterlab by clicking on a different notebook. 

Otherwise unsaved work in jupyterlab is lost and it just goes straight to NWBE without warning...

**Comment by filippomc** [comment]
When changing application, show a warning dialog

**Comment by filippomc** [comment]
To summarize: the implementation is we show a warning popup when clicking on a resource related to a different application, as the one in the picture in #838 . The popup is not needed when starting from jupyterlab as it is shown already.

**Comment by pgleeson** [comment]
See https://github.com/OpenSourceBrain/OSBv2/pull/907#issuecomment-1956372698

**Comment by filippomc** [comment]
When no current resource is selected we get an error: `Uncaught TypeError: Cannot read properties of undefined (reading 'type')`
