### ISSUE TITLE
Ignore notebooks in .ipynb_checkpoints folders when parsing for resources in workspaces

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#841]
Any of these checkpointed notebooks should be ignored, as they'll just be old copies of the main notebooks, and just confuse the resource list... e.g. https://v2.opensourcebrain.org/workspace/813
<img width="1475" alt="Screenshot 2023-12-07 at 13 51 50" src="https://github.com/OpenSourceBrain/OSBv2/assets/1556687/83c96192-e5de-408c-af50-44bae3670372">

**Comment by pgleeson** [comment]
Should be a quick fix in the file searching/resource finding code...

**Comment by filippomc** [comment]
This is the file to change @D-GopalKrishna https://github.com/OpenSourceBrain/OSBv2/blob/master/applications/workspaces/tasks/scan-workspace/main.py

**Comment by SimaoBolota-MetaCell** [comment]
The checkpointed notebooks are no longer being displayed


![Image](https://github.com/OpenSourceBrain/OSBv2/assets/99416933/cd3c76df-8eb0-4d4e-8765-dff0ef1da5c2)
