### ISSUE TITLE
Multiple tab match should be AND not OR by default

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#842]
Makes most sense that if a user specifies 2 tabs that they want results with both...

<img width="1024" alt="Screenshot 2023-12-07 at 13 25 46" src="https://github.com/OpenSourceBrain/OSBv2/assets/1556687/c9f9d5a5-dd48-4666-865e-e8a51e01e59e">

**Comment by filippomc** [comment]
@SimaoBolota-MetaCell OR is what is expected from the description, while the title says AND. @pgleeson what's the one?

**Comment by D-GopalKrishna** [comment]
Hi @SimaoBolota-MetaCell , the PR for this issue is not yet merged!
here - https://github.com/OpenSourceBrain/OSBv2/pull/863

thanks!
