### ISSUE TITLE
Nothing seems to happen when deleting workspace from workspace page

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/OSBv2#846]
Clicking on the "delete" option on the workspace page doesn't seem to do anything:

![image](https://github.com/OpenSourceBrain/OSBv2/assets/102575/742d9a6e-d8c9-4559-a7d9-49c413d9c341)

It is deleted---this workspace is no longer there---but the page doesn't change. It should probably go back to the workspaces main page?

**Comment by pgleeson** [comment]
Fixed on live
