### ISSUE TITLE
Failing to get workspace to copy files from netpyne repository

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#852]
@filippomc I've tried twice to create a workspace from this repo: https://v2.opensourcebrain.org/repositories/9#
On both occasions it failed to copy the files to the workspaces, Could you look if there is any error? Maybe it's down to the size of the repo?

**Comment by filippomc** [comment]
Logs:

```
GitHub copy master to /project_download/NetPyNE source code/
svn: E175002: Unexpected HTTP status 504 'Gateway Timeout' on '/Neurosim-lab/netpyne/branches/master'
```

**Comment by filippomc** [comment]
The command used is like `svn export   --force "https://github.com/Neurosim-lab/netpyne/branches/master" .`, which fails also locally for me

**Comment by pgleeson** [comment]
Is it due to netpyne now being at https://github.com/suny-downstate-medical-center/netpyne? Maybe the simplest solution is to remove the repo and replace with a similarly named one with the correct url.

The better solution though would be to resolve the url at Github first for the correct one, and use that... This will happen more and more in future...

**Comment by filippomc** [comment]
`svn export   --force "https://github.com/suny-downstate-medical-center/netpyne/branches/master" .` works. Might add something to follow redirects as you suggest, not sure if it's urgent though in this flavour. 

Can also edit the repository url without creating a new one.

**Comment by pgleeson** [comment]
It would be great if you could manually edit that. I'll close this when I've tested it works

GH repos might be deleted also, so maybe it's better to test availability the urls for GH (and DANDI) as part of the API repo update scripts under development here: https://github.com/OpenSourceBrain/OSBv2/tree/feature/repo_updates_via_api/libraries/client. I'll add an issue on that.

**Comment by pgleeson** [comment]
Have renewed the netpyne featured workspace, so should be all good.
