### ISSUE TITLE
For admin users: all workspaces also shown on our user profile pages

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/OSBv2#865]
On the main workspace page, my admin account can  see all ~600 workspaces, which is fine. However, on the user profile page of my admin account, I can also see everyone's public and private workspaces. I think on the user page, I should only see my workspaces, right? 

The repositories work correctly---on the user page, I only see the 4 repositories that this admin account has added.

**Comment by sanjayankur31** [comment]
Seems to be fixed on v2dev, Padraig checked.

**Comment by pgleeson** [comment]
Fixed on live
