### ISSUE TITLE
Github no longer supporting SVN: file copy to workspace broken

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#874]
Need to move to git sparse clone based file copy to workspace.
https://stackoverflow.com/questions/2466735/how-to-sparsely-checkout-only-one-single-file-from-a-git-repository

**Comment by filippomc** [comment]
Alternative solution using git:
```
git clone -n https://github.com/OpenSourceBrain/OSBv2.git --depth 1 --branch develop
cd OSBv2
git checkout HEAD [PATH]
```

This solution also creates the .git directory so allowing to pull changes from the terminal

**Comment by sanjayankur31** [comment]
> Alternative solution using git:
> 
> ```
> git clone -n https://github.com/OpenSourceBrain/OSBv2.git --depth 1 --branch develop
> cd OSBv2
> git checkout HEAD [PATH]
> ```
> 
> This solution also creates the .git directory so allowing to pull changes from the terminal

Yeh, I did think of a shallow clone, but this doesn't work for cases when users only want a subset of files, right? (Or we'll have to delete extra files after the initial clone and all that?)

**Comment by filippomc** [comment]
> Yeh, I did think of a shallow clone, but this doesn't work for cases when users only want a subset of files, right? (Or we'll have to delete extra files after the initial clone and all that?)

The -n parameter (--no-checkout) will leave freedom to checkout only what's needed afterwards with `git checkout HEAD [PATH]`

**Comment by pgleeson** [comment]
Fixed on current live implementation.
