### ISSUE TITLE
Design Repository workflows: wireframes and mockups

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#88]
The workflow includes:
- the creation of a repository from a github source (other sources will come in the future)
- browsing/searching repositories
- see repository details from README.md
- browse the files inside the repositories
- Create a new workspace from a repository file or folder
- Add a file/folder as a resource to a workspace

- [ ] Wireframes (Matteo, Filippo)
- [ ] Mockups (Paul)

**Comment by pgleeson** [comment]
Note that like an OSBv1 project it should be possible to associate metadata with a reposotory, particularly which users are members (Developer, Scientific Coordinator, see https://www.opensourcebrain.org/projects/acnet2) and a number of custon fields, e.g.
https://www.opensourcebrain.org/projects/acnet2.json
