### ISSUE TITLE
Pagination does not reset when changing between My Repositories and All Repositories

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [OpenSourceBrain/OSBv2#881]
**Describe the bug**
Pagination does not reset when changing between My Repositories and All Repositories

**To Reproduce**
1. Go to All Repositories
2. Change the page to page 4 for example
3. Go to My Repositories

**Expected behavior**
The user should be in the initial page

**Screenshots**

https://github.com/OpenSourceBrain/OSBv2/assets/99416933/a51da2f2-1d7e-4fe5-8189-34a183bb4881

**Comment by filippomc** [comment]
Would be nice to see the current page in the query string and use as a parameter
