### ISSUE TITLE
Dropdown Menu changes location When Clicking "Open Workspace" from Within Workspace Page

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [OpenSourceBrain/OSBv2#883]
**Describe the bug**
When clicking on Open Workspace when already inside the workspace page, the dropdown for the three dots menu at the top right moves across the page . This only happens when clicking 'Open Workspace'

**To Reproduce**
1. Go to Workspaces
2. Click on a workspace to open it
3. On the Workspace page click on the three dots at the top right
4. Click on Open Workspace

**Screenshots**
Example 1 - for both private and my own workspaces

https://github.com/OpenSourceBrain/OSBv2/assets/99416933/c6e6937e-9636-434e-bced-6c6b6d273e29

Example 2 

https://github.com/OpenSourceBrain/OSBv2/assets/99416933/d00966b9-b078-4dfb-81e6-71aa9f6b6a07

As you can see below it does not happen for the other Open buttons

https://github.com/OpenSourceBrain/OSBv2/assets/99416933/83d60e2b-4365-4dcb-afe0-18f81ec12b8b

**Comment by filippomc** [comment]
Could not reproduce
