### ISSUE TITLE
Enable URL form with search over specific tags or strings

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#888]
Would be very useful for saying on another page/in an email "Here's all the ModelDB repositories" or "Here's all the NetPyNE workspaces"
e.g.
https://v2.opensourcebrain.org/repositories?tag=modeldb 
https://v2.opensourcebrain.org/repositories?q=netpyne

Note if https://github.com/OpenSourceBrain/OSBv2/issues/887 is enabled, then allow

https://v2.opensourcebrain.org/workspaces?q=netpyne

**Comment by filippomc** [comment]
First implementation, we only check the query string, no automatic construction of the qs

**Comment by filippomc** [comment]
Queries:
- q=
- tags=
- types=
