### ISSUE TITLE
Limit size of workspace images/thumbnails, otherwise they hide the workspace descriptions

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/OSBv2#893]
![image](https://github.com/OpenSourceBrain/OSBv2/assets/102575/766c863e-53f1-438c-833c-cb9185aa6c50)

^description only visible after scrolling down.

if a user uploads too large a workspace image/thumbnail, the image takes up all the space and the text description gets hidden since it doesn't fit in the screen height. Maybe we should limit the size of the displayed image, so that even if users upload massive images, the description is still visible?

**Comment by filippomc** [comment]
Can set a max height to that image but have to be sure that the display is good enough for most of the workspaces in production

**Comment by sanjayankur31** [comment]
As long as it doesn't take up all the horizontal space to cause the description to be hidden, that should be fine?
