### ISSUE TITLE
Repositories page broken and jupyter not loading on v2dev

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#896]
https://www.v2dev.opensourcebrain.org/repositories

Perhaps due to a recent deployment @filippomc @D-GopalKrishna ?

**Comment by pgleeson** [comment]
Also jupyterlab is failing to open workspaces...

**Comment by sanjayankur31** [comment]
Log from devtools:

[v2dev.opensourcebrain.org-1706107391105.log](https://github.com/OpenSourceBrain/OSBv2/files/14039868/v2dev.opensourcebrain.org-1706107391105.log)

**Comment by pgleeson** [comment]
All looking good on v2dev now, so closing this unless you know of soem other issues @filippomc.
