### ISSUE TITLE
Implement core vanilla workspace application functionality

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#90]
The Vanilla application is actually a Jupyter lab application that shows the workspace directory and any other resource accessible from the pod (user space and repository in the future).
Want also to start figuring out how to personalize Jupyter lab: use a theming consistent with the rest of osb and hide/remove functionality we don't need.

- [x] Design interaction to open a workspace in the vanilla application
- [x] Implement and deploy
- [x] Investigate personalization capabilities of Jupyter lab (write outcome of the research in this card)

**Comment by filippomc** [comment]
the vanilla application is not actually related to a specific resource, so need another way to open an application on a workspace without necessarily click on a resource

**Comment by pgleeson** [comment]
True that is doesn't open with a specific resource preloaded, but then again neither does NetPyNE currently... you can just open a new netpyne ws from the current home page...

**Comment by filippomc** [comment]
Netpyne is supposed to open a resource when clicking on a resource. It will be possible when we can identify a Netpyne resource with the format settled.
I think it will also be useful to give the option to the user to open a netpyne/nwb workspace with the vanilla application: so there is not such a thing as a "netpyne" or "nwb" workspace but rather a workspace that contains resources of various types and a default application to open it (which can coincide with the last application used).
