### ISSUE TITLE
Significant latency in typing in search box on v2dev

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#920]
To reproduce, try typing in searchbox on https://v2dev.opensourcebrain.org/repositories

This was me typing `sbmlshowcase` at normal pace, seems to search on every keystroke, and often misses them

<img width="1355" alt="Screenshot 2024-03-20 at 12 07 59" src="https://github.com/OpenSourceBrain/OSBv2/assets/1556687/ec3ea0fc-b8a2-4219-9001-3483f8f19d70">

**Comment by filippomc** [comment]
Very likely related to a missing debouncing
