### ISSUE TITLE
Workspace files have wrong user/group permissions on v2dev

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#921]
Mounted as root/root, not joyvan/users, so no write access:

<img width="758" alt="Screenshot 2024-03-20 at 14 53 08" src="https://github.com/OpenSourceBrain/OSBv2/assets/1556687/d5fca281-8d53-438a-aebc-ae9312714840">

**Comment by filippomc** [comment]
The github copy workflow is failing but no error message.
Here the logs:
```
W
Download path is /project_download/2014816/main
GitHub copy  to /project_download/2014816/main
total 8
drwxr-xr-x    2 root     root          4096 Mar 26 09:19 .
drwxr-xr-x    3 root     root          4096 Mar 26 09:19 ..
Git: fix permissions
Git: cloning new repository branch: main
Cloning into '/project_download/2014816/main'...
Git: setting user/email to OSBv2 for new repo
Git: checking out everything
Your branch is up to date with 'origin/main'.
Git: checking out new branch and committing
Switched to a new branch '20240326091912-osbv2'
On branch 20240326091912-osbv2
nothing to commit, working tree clean
```

This log line is not shown -- https://github.com/OpenSourceBrain/OSBv2/blob/9bb1f51e838a79af71f06d1ddab5d6e47694af4b/applications/workspaces/tasks/github-copy/run.sh#L51

**Comment by filippomc** [comment]
Fixed: the issue was related to git commit returning 0 code and then exiting with nothing to commit

**Comment by pgleeson** [comment]
Fixed
