### ISSUE TITLE
User interface cleaning

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#94]
Remove unused interface elements:
- [x] menu items with no functionality attached
- [x] User space in toolbar
- [x] Take the tour button (unless we want to add some easy element like animated gif or video)

Find and fix any user interface defect.

- [x] When a user is logged in, user workspaces shown by default

**Comment by filippomc** [comment]
Replace text in the banner

"Open Source Brain 2 coming soon"

**Comment by pgleeson** [comment]
Specifically, replace with: "Coming soon: Open Source Brain v2.0..."

**Comment by filippomc** [comment]
@pgleeson @tarelli  Need a title and ad subtitle. What about something like

# Coming soon: Open Source Brain v2.0
Completely new with model creation, experiment exploration and interactive playgrounds...

Also maybe something like this:

# Welcome to the Open Source Brain v2.0 preview
Coming soon with new with model creation, experiment exploration and interactive playgrounds...

**Comment by tarelli** [comment]
I like the second one but final word to @pgleeson

**Comment by pgleeson** [comment]
2nd one, with:
Coming soon with NeuroML model creation, NWB data exploration and interactive playgrounds...
