### ISSUE TITLE
Netpyne adaptations

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#96]
- Set netpyne to use the workspace folder as default

**Comment by pgleeson** [comment]
I don't think we should remove the tutorials just yet, it gives a quick way to get np doing/showing something useful. Even if a user starts off a workspace with a model, they may still want to remove it, start up one of the tuorials, edit it and save that as their workspace on OSB.

**Comment by filippomc** [comment]
Proposal: since the netpyne format is not settled yet we can start we an empty netpyne workspace and use internal Netpyne functionality to load files and tutorials for now. This will reduce the estimated effort

**Comment by filippomc** [comment]
to do: the netpyne notebook must be saved inside the workspace
